### ISSUE TITLE
How to `nixos-rebuild` with edited `configuration.nix` ?

### ISSUE THREAD

**Issue by luochen1990** [nix-community/NixOS-WSL#10]
Hi, I'm trying to switch to my own configuration.nix, but failed with following error:

> You must set the option ‘boot.loader.grub.devices’ or 'boot.loader.grub.mirroredBoots' to make the system bootable.

(after ` nixos-generate-config`)

![image](https://user-images.githubusercontent.com/2309868/105328953-8f175a00-5c0b-11eb-981d-a345f94128b4.png)

Is there any suggestion?

**Comment by Trundle** [comment]
There are a few things in the repo's version of `configuration.nix` that are definitely required to make NixOS-WSL work. For example, WSL comes with its own kernel and init system, hence it won't use NixOS's grub and initrd. I would recommend to start with the provided configuration and then incorporate your changes into it.

From the error that is shown in your screenshot, my guess is that your configuration doesn't contain `boot.isContainer = true;`.

**Comment by luochen1990** [comment]
Thanks, that is very helpful.  

So, if the `configuration.nix` provided by this repo is intended to be incorporated, I'm considering making it a NixOS module, what do you think about that ?

**Comment by Trundle** [comment]
I think that makes sense! With #12 merged, the configuration is now also copied to `/etc/nixos` in the resulting tarball, so `nixos-rebuild switch` should work inside a freshly imported NixOS-WSL.

**Comment by nzbr** [comment]
The current release includes a `/etc/nixos/configuration.nix`, so I am closing this issue
