### ISSUE TITLE
Rename default user or create a new user?

### ISSUE THREAD

**Issue by chriselsner** [nix-community/NixOS-WSL#107]
I'd like to login as a user named `chris`. Is changing the `defaultUser` option the correct way to do this? Or do I need to keep `nixos` as the default user and create a new user for myself?

When I tried modifying the `defaultUser`, it created a new directory under `/home`, but without the `nix-defexpr/` and `nix-profile/` folders. `/home/nixos` was also still there but no longer accessible (I was getting a `permission denied` error when trying to `ls` or `cd`).

**Comment by nzbr** [comment]
Changing `defaultUser` is indeed the correct way. To keep the same UID (and access to the files in `/home/nixos`), you'll need to set `users.users.chris.uid = 1000;`. With the upcoming release that will happen automatically
That the `nix-defexpr` and `nix-profile` directories aren't present is normal for a new user account, they get created when you use `nix-channel` and `nix-env`. If you'd rather keep using `/home/nixos` as your home directory, you can set `users.users.chris.home = "/home/nixos";`

**Comment by chriselsner** [comment]
Thanks! After changing `defaultUser` is it safe to remove `/home/nixos`? Is there a proper way to remove that user from the system or have they been removed by simply changing the `defaultUser`?

**Comment by nzbr** [comment]
You can chack in `/etc/passwd` whether or not the user has been removed. Deleting `/home/nixos` should be safe either way

**Comment by chriselsner** [comment]
Thanks this was really helpful!
