### ISSUE TITLE
Change xserver keyboard layout does not work for WSLg

### ISSUE THREAD

**Issue by Thrimbda** [nix-community/NixOS-WSL#108]
I'm not sure if this is a bug or feature request

I have changed keyboard layout to **colemak** for xserver according to the wiki [here](https://nixos.wiki/wiki/Keyboard_Layout_Customization)

yet it dose not work for wslg application, i.e. Emacs

here is my weston.log
[weston.log](https://github.com/nix-community/NixOS-WSL/files/8917537/weston.log)

thank you.

**Comment by Thrimbda** [comment]
[this](https://github.com/microsoft/wslg/issues/27#issuecomment-922832648) is working for me as a workaound, it seems that by default emacs was launched with wayland, which explains why xserver settings not working here.

and as for the original problem, [here](https://github.com/microsoft/wslg/issues/696#issuecomment-1124045033) are some information why this happens and the potential solutions, close the issue for now as it's not an issue of this distribution.

**Comment by tmplt** [comment]
For anyone else that ends up here: starting your program with `WAYLAND_DISPLAY=` will make it fall back on XWayland, if able; e.g. `WAYLAND_DISPLAY= emacs`.
