### ISSUE TITLE
systemd default tmpfiles removes /tmp/.X11-unix/X0

### ISSUE THREAD

**Issue by nzbr** [nix-community/NixOS-WSL#114]
### Discussed in https://github.com/nix-community/NixOS-WSL/discussions/113

<div type='discussions-op-text'>

<sup>Originally posted by @myme June 26, 2022</sup>
I'm fairly certain I've been able to run `x11` apps on NixOS-WSL before, but suddenly it stopped working. Wayland apps still worked, so figured it was related to `xwayland` somehow. Found https://github.com/microsoft/wslg/issues/558 & https://randombytes.substack.com/p/wslg-on-making-wslg-and-systemd-play which seemed to describe my error case quite perfectly. `systemd-tmpfiles` is removing the `/tmp/.X11-unix` directory created by WSL and so the `X0` socket is gone.

Doing this in my config makes `x11` apps work again:

```nix
{
      systemd.tmpfiles.packages = lib.mkForce [];
}
```

I'm not sure if I'm actually relying on any of the `tmpfiles` being setup by `systemd`, but clearing the list seems a bit overkill in any case. I haven't been able to find any NixOS-WSL bugs or reports where people experience this. I'm seeing this on two different machines, so I'm curious as to why I'm not finding anybody else with this issue.

Is it a bug that should be handled through NixOS-WSL somehow or just me?</div>

**Comment by SuperSandro2000** [comment]
I have ``/tmp/.X11-unix/`` on my WSL created with root rights.

> ```nix
> {
>       systemd.tmpfiles.packages = lib.mkForce [];
> }
> ```

We should probably not clear those.

**Comment by myme** [comment]
> # or empty them at startup

I'm thinking it's this though because "startup" in this sense from `systemd`'s perspective is after `WSL` is up and running. `WSL` is populating `/tmp` _before_ `syschdemd` gets to run - which of course isn't really the case for normal `systemd` deployments where it's _real_ `PID 1` and started on boot and not after the fact in a namespace.

**Comment by nzbr** [comment]
`/tmp/.X11-unix/` exists in both cases, but without removing the tmpfiles config, the X0 socket gets removed (that is on a fresh tarball). I'm currently searching for the tmpfiles rule that is responsible for that

**Comment by nzbr** [comment]
Testing this now. NixOS specific rules are saved as `00-nixos.conf`, so they always run first

**Comment by nzbr** [comment]
Seems to work!
