### ISSUE TITLE
Add Entry in wsl.conf for manual resolv.conf settings

### ISSUE THREAD

**Issue by Saboti** [nix-community/NixOS-WSL#118]
## Problem
I have to use my own Nameserver so get Internet Access which i have to add in /etc/resolv.conf.
This only works if i add the following in /etc/wsl.conf
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false

```
## Solution
Add an option to include
```
[network]
generateResolvConf = false
```
in the /etc/wsl.conf file

**Comment by shayne** [comment]
I believe this is already available via https://github.com/nix-community/NixOS-WSL/blob/3651abbfb84b3f40f09f63a515f61aa8d49608f9/modules/wsl-distro.nix#L76

**Comment by Saboti** [comment]
> I believe this is already available via
> 
> https://github.com/nix-community/NixOS-WSL/blob/3651abbfb84b3f40f09f63a515f61aa8d49608f9/modules/wsl-distro.nix#L76

Thank you. In the last Release Version this is not included.
I assume i have to follow "Building your own system tarball" to get the last Version?

**Comment by Saboti** [comment]
Update worked as described. Thank you!
