### ISSUE TITLE
Zip installer

### ISSUE THREAD

**Issue by godalming123** [nix-community/NixOS-WSL#120]
## Problem
New user experience is bad as windows doesn't support tar.gz files

## Solution
Add a zip installer to the next release

**Comment by nzbr** [comment]
You don't need to open the `.tar.gz` file on Windows directly. It's meant to be used with `wsl --import` and that command only supports `.tar.gz`
Once we have a working DistroLauncher (see #94), there'll be a `.msix` download that can be used to install the distro on windows without manually invoking `wsl.exe`

**Comment by godalming123** [comment]
thanks
