### ISSUE TITLE
I want to upload a swap file.

### ISSUE THREAD

**Issue by PlumpMath** [nix-community/NixOS-WSL#123]
https://stackoverflow.com/questions/30887143/make-j-8-g-internal-compiler-error-killed-program-cc1plus

## Problem
There is a memory error in a specific program...(ifcopenshell build)
So I want to upload a swap file.
(windows %HOME% .wslconfig)
Also, is there a way to check?
I'm looking at several documents, but if there is a way to solve it all at once, please suggest me.
thank you

**Comment by nzbr** [comment]
If you want to add a swp file to WSL, `.wslconfig` is the right place for that.
Mine, for example looks like this:
```

**Comment by nzbr** [comment]
I hit a keyboard shortcut I didn't mean to, sorry 😅

**Comment by nzbr** [comment]
If you want to add a swp file to WSL, `.wslconfig` is the right place for that.
Mine, for example looks like this:
```ini
[wsl2]
memory=8G
swap=32GB
```
The `memory=` line is optional, if it isn't set, WSL will use half of the available memory. The `swap=` line then specifies the size of the swap file
You can check whether or not the swap file is present from within WSL by running `free -h`. The output will look something like this:
```
nzbr:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       472Mi       6.7Gi       4.0Mi       572Mi       7.1Gi
Swap:          32Gi          0B        32Gi
```
If the swap file you configured doesn't show up here, try rebooting the WSL VM by running `wsl --shutdown` in a windows shell
I hope that helps!

**Comment by PlumpMath** [comment]
@nzbr It solved as your description
thank you.
