### ISSUE TITLE
openjdk platform problem?

### ISSUE THREAD

**Issue by PlumpMath** [nix-community/NixOS-WSL#130]
It seems that the wsl nixos project is trying to use the windows native version of the jdk. (In my personal opinion, it's much better (because it's really convenient if you do nix to generate the clojure version binary that the company is using).
If I'm right,
For using openjdk (windows version) within wsl nixos.
stdenv.isWSL I wish there was a nix code like this.
Thank you

https://github.com/jlesquembre/clj-nix/issues/30

**Comment by SuperSandro2000** [comment]
The detection method of openjdk is not that great but wslpath is included since https://github.com/nix-community/NixOS-WSL/commit/e4e8d92082d19a6ea5cf7f46530e8c2e37faded5
