### ISSUE TITLE
Unable to set custom nameservers

### ISSUE THREAD

**Issue by giang-nghg** [nix-community/NixOS-WSL#132]
## Bug description
Setting custom nameservers requires `wslConf.network.generateResolvConf = false` in order to prevent WSL to overwrite your custom values, but doing so also prevents setting `network.nameservers`.

## To Reproduce

1. Set `wsl.wslConf.network.generateResolvConf = false` in `configuration.nix`
2. Set `networking.nameservers = [ <some IPs> ]`
3. Run `nix-build -A nixosConfigurations.mysystem.config.system.build.installer`

**Expected behavior**
Build successful

## Logs
```
error: The option `environment.etc.resolv.conf.source' is used but not defined.
```

**Comment by nzbr** [comment]
Can confirm that this is indeed a bug that I'm able to reproduce (I didn't notice, because I set `etc."resolv.conf".text` in my config. That might be a temporary solution for you as well until this is fixed)
