### ISSUE TITLE
How do I set up wsl audio config?

### ISSUE THREAD

**Issue by PlumpMath** [nix-community/NixOS-WSL#146]
Hello
I'm trying to log in to x with xrdp and record a sound.
How do I set up wsl audio config?

Thanks, Good-day everyone.

**Comment by nzbr** [comment]
Are you able to play audio from an application running inside WSL? If yes, the program is connected to the PulseAudio daemon and recording _should_ work as well. If it doesn't, that is a problem with WSL, not NixOS

**Comment by K900** [comment]
Is this still an issue?

**Comment by PlumpMath** [comment]
I can hear the sound well now. I apologize for not checking earlier. Thank you for the check
