### ISSUE TITLE
Cleanup after removing boot.isContainer

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-community/NixOS-WSL#149]
Follow up to https://github.com/nix-community/NixOS-WSL/pull/145

ToDos right now:
- [x] disable timesyncd
- [x] add ``powerManagement.enable = false;`` to disable the following units:
```
+ unit-post-resume.service
+ unit-post-resume.target
+ unit-pre-sleep.service
```

Wait for the following PRs:
- https://github.com/NixOS/nixpkgs/pull/197867
- https://github.com/NixOS/nixpkgs/pull/197870
- https://github.com/NixOS/nixpkgs/pull/197917
- https://github.com/NixOS/nixpkgs/pull/197922
- https://github.com/NixOS/nixpkgs/pull/197925

ToDos after that:
- set the following:
```
boot.modprobeConfig.enable = false; # maybe not required after patching top-level activation?
boot.kernel.enable = false;
console.enable = false;
hardware.console = false;
services.udev.enable = false;
```
- revert/fix workarounds introduced in #145
- cleanup nixos/modules/virtualisation/container-config.nix

other questions:

sshd.pam changed. Is that important?

```diff
-session optional pam_loginuid.so
+session required pam_loginuid.so
```

**Comment by nzbr** [comment]
The change in `sshd.pam` is necessary to get #140 to work properly

**Comment by nzbr** [comment]
udev and LVM might come in handy when dealing with external drives being attached to WSL

**Comment by SuperSandro2000** [comment]
Yes and those can all individually be enabled if required but by default I would still disable them because WSL has by default no use for them.

**Comment by SuperSandro2000** [comment]
https://github.com/nix-community/NixOS-WSL/pull/175
