### ISSUE TITLE
Systemd hangs on first boot

### ISSUE THREAD

**Issue by nzbr** [nix-community/NixOS-WSL#156]
## The Problem

There is a known issue in the latest release's installer tarball that causes the first boot to hang after the `Starting systemd...` line
The component that is responsible for this bug has been re-written and the bug does not seem to be present in the latest builds of the `main` branch. The rewrite will be included with the next release and this Issue will be closed when that happens

## Workaround

To get a working NixOS installation, follow the regular installation steps until it hangs after `Starting systemd...`.
After that, execute `wsl --shutdown` in a windows command prompt to kill your WSL VM. Please note that this will also stop anything you have running in your other WSL instances at that moment!
When you now start NixOS, it should be working

If it keeps hanging even after restarting WSL multiple times, you can try installing using `nixos-wsl-x86_64-linux.tar.gz` instead of `nixos-wsl-installer.tar.gz`

**Comment by tyoc213** [comment]
```
wsl -d NixOS
Unpacking root file system...
 307MiB 0:00:10 [28.3MiB/s] [========================================================================>] 100%
Activating nix configuration...
Copying /usr/share/applications
Copying /usr/share/icons
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
setting up /bin...
Cleaning up installer files...
finding garbage collector roots...
removing stale link from '/nix/var/nix/gcroots/auto/6yfbrv8wfkyl40wq6827lamr9m29z7wg' to '/build/nix/var/nix/profiles/per-user/root/channels-1-link'
removing stale link from '/nix/var/nix/gcroots/auto/zxi8v969la5n36bg7gs016wgcif4qjhp' to '/build/nix/var/nix/profiles/system-1-link'
deleting garbage...
deleting '/nix/store/ab5mixyq1zg0x5lnr5i7m4l5815fp1h8-wsl-prepare'
deleting '/nix/store/scr6balqjknqpgm7igd0b4pagmp2ldbl-installer.sh'
deleting '/nix/store/pmb55f6rk98cdycqf589vb3xpbg15k28-source'
deleting '/nix/store/cq6l0b0iv2y3gln3xi6nzxs57mz5rxws-tarball'
deleting '/nix/store/0p9v7yvblgxsds9pbsrir3af6gw0x77s-busybox-1.35.0'
deleting '/nix/store/5mism3qrfc3ah9ahvf7sczxy4bax9cgq-pv-1.6.20'
deleting unused links...
note: currently hard linking saves -0.00 MiB
6 store paths deleted, 309.05 MiB freed
Optimizing store...
5.74 MiB freed by hard-linking 3714 files
Starting systemd...

```

**Comment by AlexanderKyron** [comment]
This doesn't only happen on first boot for me - if I shut down the system from Linux and then start it again with wsl -d NixOS or through the Windows Terminal menu it will hang again and I need to run wsl --shutdown again, then it will load again the next time. 

To reproduce - install, run - get past initial hang as described in post with wsl --shutdown - then launch a session and shut it down with shutdown 0 - then try to start another session.

**Comment by retraut** [comment]
I have the same issue on windows 11

**Comment by ClementNerma** [comment]
Same issue here:
Windows 11 Home, build 22621.1265 (22H2), version 10.0.22621.1265
WSL 1.1.3.0
Kernel 5.15.90.1

**Comment by arrow501** [comment]
Same issue on the initial run

Microsoft Windows 10 Home 10.0.19044 N/A Build 19044
Windows version: 10.0.19044.2604
WSL version: 1.1.3.0
Kernel version: 5.15.90.1

**Comment by bartdorsey** [comment]
WSL now supports running systemd by changing a setting in /etc/wsl.conf  Would this be  a better way to get NixOS going?

**Comment by nzbr** [comment]
@bartdorsey If you are on the latest version from the `main` branch, you can already switch to using the native systemd support with `wsl.nativeSystemd = true`. It is currently opt-in, because the installer does not support it yet

**Comment by johnw42** [comment]
Just a note for anyone who's having this issue: it's still present in the `nixos-wsl-installer.tar.gz` I downloaded yesterday. The workaround still works, although it will seem to hang for a little while after starting systemd the second time, so don't panic!

**Comment by K900** [comment]
Fixed in the latest release.
