### ISSUE TITLE
boot.binfmt.emulatedSystems doesn't work

### ISSUE THREAD

**Issue by djcsdy** [nix-community/NixOS-WSL#196]
## Bug description
Setting `boot.binfmt.emulatedSystems` in `configuration.nix` doesn't work as expected, apparently because `/proc/sys/fs/binfmt_misc` is not mounted properly.

## To Reproduce
In `/etc/nixos/configuration.nix`, set:

```nix
{
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
  wsl.interop.register = true;
}
```

Run `sudo nixos-rebuild switch` to apply the changes.

systemd-binfmt reports errors immediately:

```txt
Jan 06 12:21:51 nixos systemd[1]: Starting Set Up Additional Binary Formats...
Jan 06 12:21:51 nixos systemd-binfmt[3583]: Failed to flush binfmt_misc rules, ignoring: Too many levels of symbolic links
Jan 06 12:21:51 nixos systemd-binfmt[3583]: /etc/binfmt.d/nixos.conf:1: Failed to delete rule 'WSLInterop', ignoring: Too many levels of symbolic links
Jan 06 12:21:51 nixos systemd-binfmt[3583]: /etc/binfmt.d/nixos.conf:1: Failed to add binary format 'WSLInterop': Too many levels of symbolic links
Jan 06 12:21:51 nixos systemd-binfmt[3583]: /etc/binfmt.d/nixos.conf:2: Failed to delete rule 'aarch64-linux', ignoring: Too many levels of symbolic links
Jan 06 12:21:51 nixos systemd-binfmt[3583]: /etc/binfmt.d/nixos.conf:2: Failed to add binary format 'aarch64-linux': Too many levels of symbolic links
Jan 06 12:21:51 nixos systemd[1]: systemd-binfmt.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 12:21:51 nixos systemd[1]: systemd-binfmt.service: Failed with result 'exit-code'.
Jan 06 12:21:51 nixos systemd[1]: Failed to start Set Up Additional Binary Formats.
warning: error(s) occurred while switching to the new configuration
```

Try to run an aarch64-linux binary, it will fail with `Exec format error`.

The problem is that systemd-binfmt cannot access `/proc/sys/fs/binfmt_misc`.

To see the problem, run `ls /proc/sys/fs/binfmt_misc`, it responds: `ls: cannot access '/proc/sys/fs/binfmt_misc': Too many levels of symbolic links`.

## Expected behavior
systemd-binfmt should set up additional binary formats successfully, and the resulting system should be able to execute aarch64-linux binaries.

## Workaround
```bash
sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
sudo systemctl restart systemd-binfmt
```

After running these commands, systemd-binfmt registers the additional binary formats successfully. To confirm, run `sudo systemctl status systemd-binfmt`:

```txt
● systemd-binfmt.service - Set Up Additional Binary Formats
     Loaded: loaded (/etc/systemd/system/systemd-binfmt.service; enabled; vendor preset: enabled)
     Active: active (exited) since Fri 2023-01-06 12:24:04 UTC; 9s ago
       Docs: man:systemd-binfmt.service(8)
             man:binfmt.d(5)
             https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html
             https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
    Process: 3626 ExecStart=/nix/store/dyxmql05ykvhgipv29l0vkq9xrcsxh0s-systemd-250.4/lib/systemd/systemd-binfmt (code=exi>
   Main PID: 3626 (code=exited, status=0/SUCCESS)
         IP: 0B in, 0B out

Jan 06 12:24:03 nixos systemd[1]: Starting Set Up Additional Binary Formats...
Jan 06 12:24:04 nixos systemd[1]: Finished Set Up Additional Binary Formats.
```

With this workaround I am able to execute aarch64-linux binaries successfully until the next reboot.

**Comment by SuperSandro2000** [comment]
> To see the problem, run `ls /proc/sys/fs/binfmt_misc`, it responds: `ls: cannot access '/proc/sys/fs/binfmt_misc': Too many levels of symbolic links`.

I only have WSLInterop turned on and that works for me:

```
 ▶ ls /proc/sys/fs/binfmt_misc
 register   status   WSLInterop
```

**Comment by djcsdy** [comment]
Weirdly the `mount` command in `wrapper.sh` is exactly what I'm running to workaround the problem. So I guess the mount is not taking effect for some reason.

Also I have no idea why the kernel is complaining `Too many levels of symbolic links`. There aren't any symbolic links in any part of the path `/proc/sys/fs/binfmt_misc`.

I see this suspicious line in my `/proc/mounts`:

```txt
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=45,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=835776 0 0
```

This is not familiar to me but is probably normal. But notably it appears after the `binfmt_misc` mount that was presumably created by `wrapper.sh`.

It looks like some part of systemd is mounting autofs over the existing `binfmt_misc` mount, perhaps that's the problem? I guess my workaround works because it mounts `binfmt_misc` again over the existing mounts.

I had the same experience that WSLInterop on its own works as expected, but setting `boot.binfmt.emulatedSystems` causes this problem. I've no idea why that is.

**Comment by djcsdy** [comment]
It looks like the `autofs` mount is created by `/etc/systemd/system/proc-sys-fs-binfmt_misc.automount`.

It seems like the underlying issue might be that autofs is broken and always responds `Too many levels of symbolic links`?

**Comment by K900** [comment]
Fixed upstream.
