### ISSUE TITLE
WSL now supports native systemd

### ISSUE THREAD

**Issue by sh-shahrokhi** [nix-community/NixOS-WSL#201]
## Problem
WSL now supports systemd. [ref](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/). however, enabling it is not possible with current workaround of NixOS. I was thinking maybe using it could benefit performance.

## Solution
enabling it is by adding `[boot]
systemd=true` to `/etc/wsl.conf`

**Comment by nzbr** [comment]
There already is the `wsl.nativeSystemd` option to enable it. Just editing wsl.conf would break your system, as there is no systemd binary in the place WSL looks for by default. If nix complains that the option does not exist, you might need to update by putting a fresh copy of this repo into `/etc/nixos/nixos-wsl`.
I'll close the issue but not lock it, so feel free to comment if you have any questions
