### ISSUE TITLE
Heavy builds fail without any response.

### ISSUE THREAD

**Issue by PlumpMath** [nix-community/NixOS-WSL#202]
Hello 
There is a hang when building mkvtoolnix or rust-analyzer. 
When it stops, it stops without any error log in the shell prompt, but the entire wsl is frozen.

I'm tinkering with cores and max-jobs in nix.conf.
Builds fine on xeon computer windows 10 wsl2 nixos a little over 10 years old, but slow.
The computer currently in question is windows 11 wsl2 nixos.

Thanks.

**Comment by PlumpMath** [comment]
cores = 4
    max-jobs = 1

I set the settings with and avoided the mkvtoolnix build, and now when I run the mkvtoolnix build again, it stops the same.

just... I avoid builds that don't work.

**Comment by SuperSandro2000** [comment]
This is a known problem with WSL. Only fix I know is to reboot.

**Comment by nzbr** [comment]
Had it happen to me for the first time a few days ago as well, but I didn't see anything that might have caused it

**Comment by PlumpMath** [comment]
I'm having trouble with webkitgtk depending somewhere.
Is there a way to list packages that depend on webkitgtk like gentoolkit equery... I don't know how to do that in a nix environment.
Every time this happens, I feel despair. 
I hope that the project that uses binary as much as possible will proceed, not the cache build server.

**Comment by nzbr** [comment]
The only Idea I have is that the build might run out of memory for some reason, but that's unlikely if you say it builds on similar Windows 10 computers. You can of course try [adding some swap to the WSL2 VM](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configuration-setting-for-wslconfig) and see if it helps. What does `free -h` say at the moment? Maybe MS changed how much RAM gets allocated to the VM between Windows 10 and 11

**Comment by nzbr** [comment]
![image](https://user-images.githubusercontent.com/7851175/223161893-b3470348-7644-4c53-b120-1d73c45a05e5.png)
This seems to be the likely reason! They changed it, so the memory allocation is capped at 8GB by default. So you can either increase the `memory` or the `swap` size

**Comment by PlumpMath** [comment]
You're right! Building now.  The computer is holding up for a long time,

**Comment by PlumpMath** [comment]
https://github.com/nix-community/NixOS-WSL/issues/123
It's a question I've asked before;
Using nix is so convenient that I keep losing my memory. lol

Thanks.
