### ISSUE TITLE
Integrated terminal fails to launch on vscode

### ISSUE THREAD

**Issue by Jumail** [nix-community/NixOS-WSL#215]
visual studio code has been working fine before I have updated to ```1.75.0```. When opening a directory using ```code .```  it opens properly but when I try to open the integrated terminal I get the following error dialog. 

``` The terminal process failed to launch: A native exception occurred during launch (posix_spawn failed: No such file or directory). ```

Extensions like rust-analyzer are not working properly since they aren't able to detect the packages installed in WSL.

I have also checked if it is a problem with with NixOS  or vscode but it seemed to work fine on others.

**Comment by nzbr** [comment]
What method of patching the VSCode server are you using?
Have you enabled native-systemd or are you using the container based method (which is currently the default) for launching systemd? And can you give me the output of `nixos-wsl-version`? (it might not exist if you are on the latest stable release of NixOS-WSL)

**Comment by nzbr** [comment]
I'm getting the same error now, and it looks really similar to when, in the past MS increased the nodejs version that the vscode server uses, so I expect that top be the case here again. If it is, that'll have to be fixed in the tool that patches the VSCode server for NixOS

**Comment by SuperSandro2000** [comment]
You should use https://github.com/msteen/nixos-vscode-server and 

fixed by https://github.com/msteen/nixos-vscode-server/commit/003411520f5e0feb90ea0ea001feb7d68d838f61

**Comment by shayne** [comment]
The node 18_x fix didn't work for me. New error, though. This is consistent across my NixOS installs (not just WSL).
https://github.com/msteen/nixos-vscode-server/issues/41
