### ISSUE TITLE
Make tests run on flake-updates

### ISSUE THREAD

**Issue by nzbr** [nix-community/NixOS-WSL#217]
The GitHub Actions Pipeline should be edited, so that tests will be executed on the `flake-updates` branch. It might be worth considering implementing that the branch will be merged automatically if all tests pass

**Comment by SuperSandro2000** [comment]
Then we need a bot account because the github action account does not trigger CI.

**Comment by nzbr** [comment]
How do we get one of those?

**Comment by SuperSandro2000** [comment]
"bot" just another account or we use the token of someone and commit as that person.

**Comment by nzbr** [comment]
@Mic92 can you enable [Renovate](https://github.com/apps/renovate) for this repo? I can see that it's already installed for something else in `nix-community`, but I think I don't have permission to enable it for here myself

**Comment by Mic92** [comment]
@nzbr enabled.

**Comment by nzbr** [comment]
Thank you!

**Comment by Mic92** [comment]
I had issues with updating flakes with the hosted renovate. Let me know if this works for you.
Otherwise I think we should create an upstream issue.

**Comment by nzbr** [comment]
I wanted to edit the renovate config before merging it, but I don't have push access to branches on this repo
```
PS C:\Users\nzbr\Projekte\NixOS-WSL> git push
ERROR: Permission to nix-community/NixOS-WSL.git denied to nzbr.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The remote is `git@github.com:nix-community/NixOS-WSL.git`, so that should be fine. However, I've noticed in the past that I'm able to commit to the repo by using the vscode on github.dev

**Comment by Mic92** [comment]
If you add:

```
permissions:
  pull-requests: write
  contents: write
```

to the github action than you should be able to push.
If the ssh remote does not work, try using $GITHUB_TOKEN with the https remote of github (there was some documentation around on how to use api keys for pushing to github).

**Comment by nzbr** [comment]
Pushing via HTTPS works, thanks for the hint.

As for renovate: It seems that it's indeed broken at the moment. It fails to update `flake.lock`, apparently due to a problem with the API token. I get the same error on [my own nixos config repo](https://github.com/nzbr/nixos) now, where I had been using Renovate without problems until recently
From the [renovate logs](https://developer.mend.io/github/nix-community/NixOS-WSL/-/job/2bbaa982-de9e-4985-aa56-c29ea8e0eb5a):
```
Command failed: docker run --rm --name=renovate_a_sidecar --label=renovate_a_child -v "/tmp/worker/a381c3/4c87f4/repos/github/nix-community/NixOS-WSL":"/tmp/worker/a381c3/4c87f4/repos/github/nix-community/NixOS-WSL" -v "/tmp/worker/a381c3/4c87f4/cache":"/tmp/worker/a381c3/4c87f4/cache" -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w "/tmp/worker/a381c3/4c87f4/repos/github/nix-community/NixOS-WSL" ghcr.io/containerbase/sidecar bash -l -c "install-tool nix 2.16.1 && nix     --extra-experimental-features nix-command     --extra-experimental-features flakes --extra-access-tokens github.com=**redacted** flake lock --update-input nixpkgs"
warning: '/nix/var/nix' does not exist, so Nix will use '/home/ubuntu/.local/share/nix/root' as a chroot store
warning: Git tree '/tmp/worker/a381c3/4c87f4/repos/github/nix-community/NixOS-WSL' is dirty
error:
       … while updating the lock file of flake 'git+file:///tmp/worker/a381c3/4c87f4/repos/github/nix-community/NixOS-WSL'

       … while updating the flake input 'nixpkgs'

       … while fetching the input 'github:NixOS/nixpkgs/nixos-23.05'

       error: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/commits/nixos-23.05': HTTP error 401

       response body:

       {
         "message": "Bad credentials",
         "documentation_url": "https://docs.github.com/rest"
       }
```

**Comment by K900** [comment]
We have Renovate now.
