### ISSUE TITLE
Set up nix channels

### ISSUE THREAD

**Issue by nzbr** [nix-community/NixOS-WSL#224]
Instead of putting the WSL specific code into `/etc/nixos/nixos-wsl` it should be distributed as a nix channel. That way, updating would be as simple as running `nix-channel --update` and `nixos-rebuild switch`.
To accomplish this, the CI pipeline should be extended to package the repo and publish those artifacts to GitHub pages (using the artifact method, not the github-pages branch). Furthermore, the commit hash should be embedded into the channel tarballs.
The default `configuration.nix` and the installer would need to be adjusted as well to load the channel.

**Comment by SuperSandro2000** [comment]
That is using the new github pages that do not get added to our git repo?

**Comment by nzbr** [comment]
That's the plan, yes

**Comment by K900** [comment]
Fixed in 23.05.
