### ISSUE TITLE
Unable to execute commands within NixOS WSL2 distribution from an elevated shell with `wsl --`

### ISSUE THREAD

**Issue by zanecodes** [nix-community/NixOS-WSL#229]
## Bug description

I'm unable to run any commands within my NixOS WSL2 distribution using the `wsl` command in an elevated shell.
I suspect this is related to `syschdemd` but I've not dug in deeply enough to know exactly why.
It does not occur with any of my other WSL2 distributions, nor does it occur in non-elevated shells.
Unfortunately, it [prevents me from using `usbipd wsl` subcommands](https://github.com/dorssel/usbipd-win/issues/561) to attach my host USB devices to NixOS, though I can still use `usbipd bind` to do so.
I have also tried using `--shell-type login` and `--shell-type none` for `wsl` to no avail.

## To Reproduce

Open an elevated PowerShell session
Run `wsl --distribution NixOS -- ls /`

**Expected behavior**

Correct output from `ls /` command, e.g.

```
PS C:\Users\Zane> wsl --distribution NixOS -- ls /
bin   dev  home  lib    lib64   lost+found  mnt  opt   root  sbin  srv  tmp  var  boot  etc  init  lib32  libx32  media       nix  proc  run   snap  sys  usr
```

## Logs
```
PS C:\Users\Zane> wsl --distribution NixOS -- ls /
nsenter: reassociate to namespace 'ns/mnt' failed: Invalid argument
```

**Comment by SuperSandro2000** [comment]
Are you using the latest code from HEAD?

**Comment by zanecodes** [comment]
Yes, I updated to HEAD from what I was on previously (13f5b22) to see if any of the recent work resolved it, but no luck there unfortunately.

**Comment by nzbr** [comment]
Just to be sure: what do `nixos-version` and `nixos-wsl-version` print?

Your command works just fine for me
```
PS C:\Users\nzbr> wsl --distribution NixOS -- ls /
bin  drv               etc   init   lost+found  nix  proc  run   srv  tmp  var
dev  drv.wsl-wrappers  home  lib64  mnt         opt  root  sbin  sys  usr
```

(`22.11.20230225.7076110 (Raccoon)` and `NixOS-WSL DEV_BUILD 4640199aeafcbb63cfbe8318bdf06f4402134f66 syschdemd`)

**Comment by zanecodes** [comment]
```
[nixos@nixos:/etc/nixos]$ nixos-version
23.05.20230119.d7705c0 (Stoat)

[nixos@nixos:/etc/nixos]$ nixos-wsl-version
NixOS-WSL DEV_BUILD dirty syschdemd
```

Interesting; I initially installed NixOS using `wsl --import` after building the installer `.tar.gz` using `nix build` within an Ubuntu20.04LTS WSL2 VM, and yesterday I updated it by renaming my old `/etc/nixos/nixos-wsl` and then doing a `git clone` of this repo into my `/etc/nixos/nixos-wsl` directory, and also had to remove the `.git` directory because I was getting errors with `fetchTree` during my `sudo nixos-rebuild switch`.

I have messed with my system `flake.nix` a bit so it's possible I just broke something important!

**Comment by zanecodes** [comment]
Didn't have time to investigate this in depth, but I recently updated my system `flake.nix` to point directly to this repo's flake and rebuilt my system, and everything's working great now, including native systemd. Thanks for looking at this and for all your hard work on this project!
