### ISSUE TITLE
networking.extraHosts doesn't work

### ISSUE THREAD

**Issue by zeratax** [nix-community/NixOS-WSL#230]
## Bug description
Just using `networking.extraHosts` will not change the `/etc/hosts` file since that one is by default managed by WSL. 

## To Reproduce
set
`config.networking.extraHosts = 'test 127.0.0.1'` 

**Expected behavior**
I think either there should be an assertion that makes sure that `wsl.wslConf.network.generateHosts` and `networking.extraHosts` aren't set together, or even more ideally would be ofc a solution where we could still append to the wsl hosts config ^^

**Comment by SuperSandro2000** [comment]
We already have https://github.com/nix-community/NixOS-WSL/blob/c6f663e8583912059605b55c07583b6e96b5e690/modules/wsl-distro.nix#L78-L85 . Not to sure how good the UX would be with an additional assert.

**Comment by nzbr** [comment]
There should probably be a warning, when you try to use `extraHosts` while `wsl.wslConf.network.generateHosts` is true
