### ISSUE TITLE
nativeSystemd enabled causes vscode to not be able to correctly start wsl

### ISSUE THREAD

**Issue by purepani** [nix-community/NixOS-WSL#231]
## Bug description
When enabling nativeSystemd, and trying to use vscode to connect to WSL, the startup script fails, in that it seems to not have access to any of the commands you would expect(saying uname is not a command, etc.)

## To Reproduce
Enable nativeSystemd. Try to connect to NixOS through the WSL extension. It should fail.

## Logs
*will attach later, not currently at computer, but didn't want to forget to submit this*

**Comment by nzbr** [comment]
This looks like #213 to me. You can check if the snippet from the last comment there helps you. If it does, we might need to add those packages to the default environment

**Comment by purepani** [comment]
> This looks like #213 to me. You can check if the snippet from the last comment there helps you. If it does, we might need to add those packages to the default environment

Hello, I was able to get rid of those errors with this script, so it seems to have progressed, but now it seems like NIX-LD is unable to set the environment variables for some reason.

**Comment by nzbr** [comment]
Microsoft pushed an update that broke VSCode on NixOS-WSL, see #238, so it might be that as well now

**Comment by purepani** [comment]
I luckily had learned about that because of that issue(Thanks for pinning it!), and downgraded the wsl extension so that this issue wouldn't exist. I also know it isn't the issue because it works just fine if I use the exact same VS code setup while only changing the native systemd setting.

**Comment by K900** [comment]
Let's keep all the VSCode discussions to #238.
