### ISSUE TITLE
How can I change the hostname?

### ISSUE THREAD

**Issue by luochen1990** [nix-community/NixOS-WSL#24]
I find that setting `networking.hostName` only works after `sudo nixos-rebuild switch`, and when I reboot the wsl with `wsl --shutdown`,  it turn back to the Windows hostname again.

So, am I expected to keep the hostname and not touching it ?

**Comment by Trundle** [comment]
The hostname is set by WSL on boot. You can create a file `/etc/wsl.conf` with the following contents to set a custom hostname:

```ini
[network]
hostname = yournewname
```

It's not super well documented though, so I don't know if it has some other side-effects.

Maybe it makes sense to manage `/etc/wsl.conf` through `NixOS-WSL` after modularisation (#10 / #19) is done? :thinking:

**Comment by nzbr** [comment]
This is now possible through `wsl.wslConf.network.hostname`

**Comment by nzbr** [comment]
@Atry It is
