### ISSUE TITLE
Add support for udev

### ISSUE THREAD

**Issue by np** [nix-community/NixOS-WSL#241]
This is related to this discussion #110

## Problem

usbip almost work for me in NixOS-WSL, enabling udev and installing the udev rules seems to be the last missing piece.

## Solution

Commenting ` systemd-udevd.enable = false;` from `/etc/nixos/nixos-wsl/modules/wsl-distro.nix` is almost working for me.
However I don't see any `/etc/udev` and don't know how populate it.

**Comment by nzbr** [comment]
You can try
```nix
{
  services.udev.enable = true;
}
```
that at least seemed to work for me

**Comment by np** [comment]
I'm on 22.05 and it does not know this option.

With unstable I got the following:

```
    'github:NixOS/nixpkgs/0874168639713f547c05947c76124f78441ea46c' (2023-01-01)
  → 'github:NixOS/nixpkgs/0d8145a5d81ebf6698077b21042380a3a66a11c7' (2023-05-04)
error: The option `services.udev.enable' has conflicting definition values:
       - In `/nix/store/80wk9aicsm80yw6djc0vqzrqygzakjc5-source/configuration.nix': true
       - In `/nix/store/gdflzjv86wsbyfz59ddqkir0k2npw95q-source/nixos/modules/virtualisation/container-config.nix': false
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

I used `lib.mkForce` and got something working.

Yet to me it is not clear which version is supposed to work as you mentionned.
