### ISSUE TITLE
after import nixos into wsl, the docker-desktop stuck at starting forever

### ISSUE THREAD

**Issue by yswtrue** [nix-community/NixOS-WSL#248]
## Bug description

after import nixos into wsl, the docker-desktop stuck at starting forever
## To Reproduce
- build latest installer
- import wsl
-  restart docker-desktop

**Expected behavior**

docker-desktop can start normally
## Logs
```
There are no logs in docker 
```

**Comment by nzbr** [comment]
I think this is the same issue as #235
