### ISSUE TITLE
Time is not updated when computer sleep

### ISSUE THREAD

**Issue by uzytkownik** [nix-community/NixOS-WSL#273]
## Bug description
Time is not updated when computer sleeps. This is probably because ntp (timesync) is disabled. Enabling chrony fixed the problem but it should work out of the box.

## To Reproduce
1. Install nix on WSL
2. Suspend computer

**Expected behavior**
Time is updated in NixOS

## Logs
N/A

**Comment by SuperSandro2000** [comment]
timesynced should be enabled since https://github.com/nix-community/NixOS-WSL/commit/e6b2332afa4d70c46ee166fc8819f61d3d9b8fca

**Comment by K900** [comment]
Should be fixed, also some workarounds added upstream, closing.
