### ISSUE TITLE
Error setting up with nixos-wsl-x86_64-linux.tar.gz

### ISSUE THREAD

**Issue by lumikalt** [nix-community/NixOS-WSL#275]
## Bug description

When trying to use the installer tarball, it hung on systemd, therefore I tried the x86_64 one. However, it too failed, with an error in the build process.

## To Reproduce
- `wsl --import NixOS . .\nixos-wsl-x86_64-linux.tar.gz`
- `wsl -d NixOS`

**Expected behavior**

Working system.

## Logs
```
PS C:\Users\lumim\NixOS> wsl --import NixOS . .\nixos-wsl-x86_64-linux.tar.gz
Import in progress, this may take a few minutes.
The operation completed successfully.


PS C:\Users\lumim\NixOS> wsl -d NixOS
<3>WSL (8) ERROR: CreateProcessParseCommon:756: getpwuid(0) failed 2
Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:324: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:504: execvpe /bin/sh failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:507: Create process not expected to return
```

checksum:
4776aa5115edb422763736f63eb9452479c4214d33f46c3b26659c77963ced25  nixos-wsl-x86_64-linux.tar.gz

**Comment by nzbr** [comment]
Have you tried `wsl --shutdown` and then `wsl -d nixos`? Rebooting the WSL VM helps sometimes

Or just try the version from the main branch until we get a new release out. You can find that here: https://github.com/nix-community/NixOS-WSL/actions/runs/5692837838. Download the `installer` artifact from the bottom of that page and unpack it. It should contain a fresh `nixos-wsl-installer.tar.gz`

**Comment by lumikalt** [comment]
Shutting down to restart it just made it error as seemingly the build was invalid. I'll try the latest artifact and report.

**Comment by lumikalt** [comment]
Latest works, cheers!

**Comment by nzbr** [comment]
Glad I could help you!
