### ISSUE TITLE
`wsl --exec <command>` doesnt work

### ISSUE THREAD

**Issue by Sakooooo** [nix-community/NixOS-WSL#284]
## Bug description

when trying to run wsl --exec with nixos as my default distro it errors with 
```
<3>WSL (16121) ERROR: CreateProcessEntryCommon:577: execvpe emacs failed 2
<3>WSL (16121) ERROR: CreateProcessEntryCommon:586: Create process not expected to return
```

## To Reproduce
1. Run `wsl --exec <command>`
2. returns <3>WSL (16121) ERROR: CreateProcessEntryCommon:577: execvpe emacs failed 2

**Expected behavior**

it should execute normally

## Logs
```
 ~ wsl --exec emacs
<3>WSL (16121) ERROR: CreateProcessEntryCommon:577: execvpe emacs failed 2
<3>WSL (16121) ERROR: CreateProcessEntryCommon:586: Create process not expected to return
~
```

**Comment by Sakooooo** [comment]
its supposed to be `wsl <command>` not `wsl --exec <command>` sorry :P

**Comment by nzbr** [comment]
`wsl --exec` actually launches the command without a login shell. Because all of the NixOS specific magic (currently, that's gonna change) happens in the login shell of the root user, only `wsl <command>` works properly with NixOS right now

**Comment by Sakooooo** [comment]
alright thanks :)
