### ISSUE TITLE
Channels require update in fresh install

### ISSUE THREAD

**Issue by TeofilC** [nix-community/NixOS-WSL#313]
## Bug description
I've just done a fresh install using the latest tarball, but it looks like the channels are missing their data.
`sudo nix-channel --update` fixes it. But it would be good to include some initial channel data that the image was built from. I can imagine something like this really confusing a beginner.

## To Reproduce
1. Do a fresh install
2. Run `nix-shell -p vim`

**Expected behavior**
It succeeds.

## Logs
```
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:25:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (<nixos>.vim) ]; } ""
             |                         ^
(use '--show-trace' to show detailed location information)
```

This is the release I used: https://github.com/nix-community/NixOS-WSL/releases/tag/23.5.5.2

**Comment by TeofilC** [comment]
If this sounds like something we'd like to have I'd be happy to make an PR to fix this

**Comment by SuperSandro2000** [comment]
> But it would be good to include some initial channel data that the image was built from.

I'd rather add the default channels and run a nixos-channel --update or just only use flakes.

Also we already have https://github.com/nix-community/NixOS-WSL/blob/main/modules/welcome.nix#L6 which should instruct users what to do.

**Comment by TeofilC** [comment]
I don't seem to get the welcome message. Maybe the release tarballs don't have that setting enabled somehow?

The welcome message seems adequate to me though.

**Comment by SuperSandro2000** [comment]
Do you overwrite `programs.bash.loginShellInit` https://github.com/nix-community/NixOS-WSL/blob/5da7c4fd0ab9693d83cae50de7d9430696f92568/flake.nix#L34 ?

**Comment by TeofilC** [comment]
Oh I see I downloaded the most recent release but the welcome message was added after!

**Comment by TeofilC** [comment]
I've tried using artefacts from HEAD and it works.
Alright I think there's nothing to do here. Thanks for your help @SuperSandro2000
