### ISSUE TITLE
Needs starting it as administrator (maybe a documentation issue)

### ISSUE THREAD

**Issue by con-f-use** [nix-community/NixOS-WSL#314]
## Bug description

I followed the steps in the readme, downloading `23.5.5.2` and running the import command on a fresh Windows 11 installation. When I tried `wsl -d NixOS` nothing happend. When I started powershell as administrator and ran `wsl -d NixOS` again, it worked. No idea if that is the intended behavior and it's just not mentioned (or I overlooked it) or if it's a problem.

**Comment by SuperSandro2000** [comment]
Are you on some enterprise device where they could have messed with policies?

**Comment by con-f-use** [comment]
Potentially yes, that could be it. I'll check when I'm at that device again. That being said, it would maybe still worth a note to put prominently in the readme. Also, I've hat no problems with other WSL images, be it official or custom.

**Comment by SuperSandro2000** [comment]
> it would maybe still worth a note to put prominently in the readme.

I don't know what helpful we could write into that. We only change the OS disk, nothing about how WSL is executed and I have no idea what could be causing this. 

Also since I hear about this the first time, it is likely something about your environment.
