### ISSUE TITLE
Where is the username set?

### ISSUE THREAD

**Issue by madorian** [nix-community/NixOS-WSL#317]
There is a user with ID 1000, but this is not set in configuration.nix

Where is this set?;)

**Comment by SuperSandro2000** [comment]
via wsl.defaultUser here https://github.com/nix-community/NixOS-WSL/blob/main/modules/wsl-distro.nix#L19

**Comment by madorian** [comment]
Right, but is this file referenced from configuration.nix or how do I access it? I'm already running NixOS-WSL, so I'm not trying to create a new one.

**Comment by SuperSandro2000** [comment]
You can change the option like any other nixos option to anything else. Then make sure the user exists and rebuild.
