### ISSUE TITLE
Does running .exe's still work with the custom init system?

### ISSUE THREAD

**Issue by lithdew** [nix-community/NixOS-WSL#32]
Apologies in advance for posting the question in the title as an issue (didn't notice anywhere I could post questions regarding this repo), though I'm looking to migrate from NixOS to Windows w/ WSL2 + NixOS and wanted to know if this is doable.

The use case is for writing Windows code in WSL2, and debugging them directly on Windows. As of now w/ NixOS, I use Wine to debug Windows code I write.

**Comment by sarahhodne** [comment]
It doesn't seem to work for me. The path isn't forwarded like usual, but even running with the full path I don't get any output from running .exes:

```
➜ /mnt/c/Windows/System32/ipconfig.exe

➜
```

Also, if anyone else is having issues with `/mnt/c` not automounting, try adding `tzdata` to your `environment.systemPackages` and this to your `/etc/wsl.conf` (inside the NixOS FS):

```ini
[automount]
enabled = true
options = "metadata,uid=1000,gid=100,noauto,x-systemd.automount"
```

**Comment by sarahhodne** [comment]
I got it to work, you need to forward some environment variables through `syschdemd.sh`, something like this seems to work for me:

```bash
# ...this is replacing the very last line of syschdemd.sh, the `exec $sw/nsenter...`
exportCmd="export WSLENV=\"$WSLENV\"; export WT_SESSION=\"$WT_SESSION\"; export WT_PROFILE_ID=\"$WT_PROFILE_ID\"; export WSL_INTEROP=\"$WSL_INTEROP\""
exec $sw/nsenter -t $(< /run/systemd.pid) -p -m -- $sw/machinectl -q --uid=@defaultUser@ shell .host /bin/sh -c "cd \"$PWD\"; $exportCmd; exec $cmd"
```

There's probably some nicer way of doing it, though.

**Comment by lithdew** [comment]
> I got it to work, you need to forward some environment variables through `syschdemd.sh`, something like this seems to work for me:
> 
> ```shell
> # ...this is replacing the very last line of syschdemd.sh, the `exec $sw/nsenter...`
> exportCmd="export WSLENV=\"$WSLENV\"; export WT_SESSION=\"$WT_SESSION\"; export WT_PROFILE_ID=\"$WT_PROFILE_ID\"; export WSL_INTEROP=\"$WSL_INTEROP\""
> exec $sw/nsenter -t $(< /run/systemd.pid) -p -m -- $sw/machinectl -q --uid=@defaultUser@ shell .host /bin/sh -c "cd \"$PWD\"; $exportCmd; exec $cmd"
> ```
> 
> There's probably some nicer way of doing it, though.

Awesome that you got it working though! I'll have a try then after migrating to Windows. Thanks!
