### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by anderspapitto** [nix-community/NixOS-WSL#36]
I installed from a release tarball some time ago, and now I see that improvements have been made. How do I update my existing container to the current version of NixOS-WSL?

In particular, if I figure out a fix to #35 , I don't know how to test or apply my fix.

**Comment by Congee** [comment]
The prebuilt one for now https://github.com/Trundle/NixOS-WSL/releases/tag/20.09-0cfd08f4881 is outdated as some patches have not been baked in. Installing a custom build tarball results in the notorious "Unspecified error".

So, I have run out of way of upgrading. :confused:

**Comment by nzbr** [comment]
With the new releases, I have provided instructions on how to update from previous versions. If you have a setup that is not covered in the release notes and need assistance with updating, please open a discussion in the "Q&A" category
