### ISSUE TITLE
Possibilty to add search entry when /etc/resolv.conf is generated

### ISSUE THREAD

**Issue by 573** [nix-community/NixOS-WSL#389]
## Problem

I am running NixOS-WSL at work behind an Anyconnect-VPN. So far I can use all the defaults NixOS-WSL brings regarding resolv.conf and would very much like to keep it like that.

Now there is one additional requirement that certain interank service is not accessed by its FQDM thus I needed something like `search our-service.enterprise.org` added to the generated resolv.conf entries.

## Solution

Not yet a solution but brainstorming, could an attribute `extraResolvconfConfig` be added accordingly ? It could have a warning that consistency is not guaranteed when someone added contradictive stuff.

**Comment by nzbr** [comment]
Are you using the `resolv.conf` generated by WSL? If yes, then I don't think it's possible to add anything to it, because NixOS doesn't generate it in the first place. With the other methods, you get exactly the same options as on bare-metal NixOS

**Comment by 573** [comment]
Basically my use case now boils down to having dns in a docker container.

I can continue to let `resolv.conf` be generated by WSL and just add `--dns-search our-service.enterprise.org` when I call `docker run`.

To complete this minimal viable example, obviously `wsl-vpnkit` has to run as well when I'm behind a VPN.
