### ISSUE TITLE
Symbolic Link Error When Using `wsl.useWindowsDriver`

### ISSUE THREAD

**Issue by pupbrained** [nix-community/NixOS-WSL#390]
## Bug description
When trying to use the `wsl.useWindowsDriver` option in my NixOS WSL configuration, the rebuild fails with:
```
ln: failed to create symbolic link '/nix/store/dkwgqmk9mnv1337kjm3kwa9qhz9401g6-wsl-lib/lib': File exists
```

## To Reproduce
1. Add `wsl.useWindowsDriver = true` to NixOS configuration.
2. Run `nixos-rebuild switch`.

## Logs
In description

## WSL version
```
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2861
```

**Comment by SuperSandro2000** [comment]
Please update, this got fixed by #383
