### ISSUE TITLE
Mount path /tmp/.X11-unix/X0 is not canonical (contains a symlink)

### ISSUE THREAD

**Issue by JojOatXGME** [nix-community/NixOS-WSL#427]
## Bug description

The initial execution of `nixos-rebuild switch` failed directly after installing NixOS-WSL. (Might be related to #420)
![nixos-wsl-cannot-mount](https://github.com/nix-community/NixOS-WSL/assets/1288216/f5ae50e3-1ce7-46c0-89e6-e05a67e7b5a0)

## To Reproduce

Here are the steps I took:

 1. Update WSL by running  
    `wsl --update`
 2. Install NixOS-WSL  
    `wsl --import NixOS C:\ProgramData\NixOS\ .\Downloads\nixos-wsl.tar.gz --version 2`
 3. Start NixOS-WSL  
    `wsl -d NixOS`
 4. Run the initial rebuild
    `sudo nix-channel --update` and `sudo nixos-rebuild switch --upgrade`

With the first step (`wsl --update`), I have installed the WSL version from the Microsoft Store. I only had the Windows-Feature-Version previously.

## Workaround

As a workaround, you may delete the symlink which causes the error.

```shell
sudo rm /tmp/.X11-unix
```

Afterwards, retry `nixos-rebuild`. This time it should complete without running into the error.

```shell
sudo nixos-rebuild switch
```

## Logs

<details>
<summary>Click to see all my interactions with the terminal</summary>

```
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

PS C:\Users\jojo> wsl --version
Ungültige Befehlszeilenoption: --version
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Verwendung: wsl.exe [Argument] [Options...] [CommandLine]
[...]
PS C:\Users\jojo> wsl --update
Installation: Windows-Subsystem für Linux
Windows-Subsystem für Linux wurde installiert.
PS C:\Users\jojo> wsl --version
WSL-Version: 2.0.9.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.4046
PS C:\Users\jojo> wsl --help
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.
Datenschutzinformationen zu diesem Produkt finden Sie unter https://aka.ms/privacy.

Syntax: wsl.exe [Argument] [Optionen...] [Befehlszeile]
[...]
PS C:\Users\jojo> wsl --status
Standard-Distribution: Ubuntu
Standardversion: 2
PS C:\Users\jojo> wsl --list
Windows Subsystem für Linux-Distributionen:
Ubuntu (Standard)
PS C:\Users\jojo> wsl --list --all -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
PS C:\Users\jojo> wsl --list --all -v -o
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.
Datenschutzinformationen zu diesem Produkt finden Sie unter https://aka.ms/privacy.

Syntax: wsl.exe [Argument] [Optionen...] [Befehlszeile]
[...]
PS C:\Users\jojo> wsl --list --all -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
PS C:\Users\jojo> wsl --import NixOS C:\ProgramData\NixOS\ .\Downloads\nixos-wsl.tar.gz --version 5                     Eine Versionsnummer konnte nicht analysiert werden.
Error code: Wsl/ERROR_VERSION_PARSE_ERROR
PS C:\Users\jojo> wsl --import NixOS C:\ProgramData\NixOS\ .\Downloads\nixos-wsl.tar.gz --version 3
Eine Versionsnummer konnte nicht analysiert werden.
Error code: Wsl/ERROR_VERSION_PARSE_ERROR
PS C:\Users\jojo> wsl --import NixOS C:\ProgramData\NixOS\ .\Downloads\nixos-wsl.tar.gz --version 2
Import wird ausgeführt. Dieser Vorgang kann einige Minuten dauern.
Der Vorgang wurde erfolgreich beendet.
PS C:\Users\jojo> wsl --list --all -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
  NixOS     Stopped         2
PS C:\Users\jojo> wsl -d NixOS
Welcome to your new NixOS-WSL system!

Please run `sudo nix-channel --update` and `sudo nixos-rebuild switch` now, to ensure you're running the latest NixOS and NixOS-WSL versions.

If you run into issues, please report them on our Github page at https://github.com/nix-community/NixOS-WSL or come talk to us on Matrix at #wsl:nixos.org.

❄️ Enjoy NixOS-WSL! ❄️

Note: this message will disappear after you rebuild your system. If you want to see it again, run `nixos-wsl-welcome`.

[nixos@nixos:/mnt/c/Users/jojo]$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-23.11
nixos-wsl https://github.com/nix-community/NixOS-WSL/archive/refs/heads/main.tar.gz

[nixos@nixos:/mnt/c/Users/jojo]$ sudo nix-channel --update
this derivation will be built:
  /nix/store/4s854ijn7z0bmx2aqv7gzk06g90c0i2d-nixos-wsl.drv
building '/nix/store/4s854ijn7z0bmx2aqv7gzk06g90c0i2d-nixos-wsl.drv'...
unpacking channels...

[nixos@nixos:/mnt/c/Users/jojo]$ sudo nixos-rebuild switch --upgrade
unpacking channels...
this derivation will be built:
  /nix/store/p6wy471d0s9d82xq5vv4wshaxdibbsgi-nixos-rebuild.drv
[...]
building '/nix/store/f2z6hpp4dyap2rmjx0mpkwq47v4y17sc-nixos-wsl-utils-1.0.0.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/b8ljdcq8ba6d8yinpadayxfx7323bf6v-utils
source root is utils
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /build/utils/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
Running phase: buildPhase
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/cc HOST_CXX=/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/c++ cargo build -j 8 --target x86_64-unknown-linux-gnu --frozen --profile release
   Compiling libc v0.2.153
   Compiling proc-macro2 v1.0.78
   Compiling bitflags v2.4.2
   Compiling rustix v0.38.31
   Compiling linux-raw-sys v0.4.13
   Compiling unicode-ident v1.0.12
   Compiling utf8parse v0.2.1
   Compiling anstyle-parse v0.2.3
   Compiling gimli v0.28.1
   Compiling cfg_aliases v0.1.1
   Compiling anstyle-query v1.0.2
   Compiling adler v1.0.2
   Compiling memchr v2.7.1
   Compiling colorchoice v1.0.0
   Compiling cfg-if v1.0.0
   Compiling anstyle v1.0.6
   Compiling miniz_oxide v0.7.2
   Compiling quote v1.0.35
   Compiling cc v1.0.83
   Compiling syn v2.0.48
   Compiling object v0.32.2
   Compiling nix v0.28.0
   Compiling is-terminal v0.4.10
   Compiling anstream v0.3.2
   Compiling clap_lex v0.5.1
   Compiling anyhow v1.0.80
   Compiling rustc-demangle v0.1.23
   Compiling strsim v0.10.0
   Compiling backtrace v0.3.69
   Compiling heck v0.4.1
   Compiling addr2line v0.21.0
   Compiling clap_builder v4.3.24
   Compiling log v0.4.20
   Compiling once_cell v1.19.0
   Compiling kernlog v0.3.1
   Compiling clap_derive v4.3.12
   Compiling clap v4.3.24
   Compiling nixos-wsl-utils v0.1.0 (/build/utils)
    Finished release [optimized] target(s) in 17.06s
Executing cargoInstallPostBuildHook
Finished cargoInstallPostBuildHook
Finished cargoBuildHook
Running phase: checkPhase
Executing cargoCheckHook
++ cargo test -j 8 --profile release --target x86_64-unknown-linux-gnu --frozen -- --test-threads=8
   Compiling nixos-wsl-utils v0.1.0 (/build/utils)
    Finished release [optimized] target(s) in 0.48s
     Running unittests src/split_path.rs (target/x86_64-unknown-linux-gnu/release/deps/split_path-ae966eef030fc8c0)

running 4 tests
test tests::exactly_one ... ok
test tests::include_interop ... ok
test tests::simple ... ok
test tests::spicy_escapes ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/shim.rs (target/x86_64-unknown-linux-gnu/release/deps/systemd_shim-afdd7ac7a354bf5f)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Finished cargoCheckHook
Running phase: installPhase
Executing cargoInstallHook
Finished cargoInstallHook
Running phase: fixupPhase
shrinking RPATHs of ELF executables and libraries in /nix/store/vb0013rcj49w7j4mhbblpilql98knmis-nixos-wsl-utils-1.0.0
shrinking /nix/store/vb0013rcj49w7j4mhbblpilql98knmis-nixos-wsl-utils-1.0.0/bin/systemd-shim
shrinking /nix/store/vb0013rcj49w7j4mhbblpilql98knmis-nixos-wsl-utils-1.0.0/bin/split-path
checking for references to /build/ in /nix/store/vb0013rcj49w7j4mhbblpilql98knmis-nixos-wsl-utils-1.0.0...
patching script interpreter paths in /nix/store/vb0013rcj49w7j4mhbblpilql98knmis-nixos-wsl-utils-1.0.0
stripping (with command strip and flags -S -p) in  /nix/store/vb0013rcj49w7j4mhbblpilql98knmis-nixos-wsl-utils-1.0.0/binbuilding '/nix/store/qs8zx0rrf6ngkrpg9f1a5cmkm927z601-set-environment.drv'...
building '/nix/store/8bjmhk3yibzdl315f242kldd83blawy0-etc-profile.drv'...
building '/nix/store/r0h9ksxafmxd6x8j8m7rliibyavz0svz-etc.drv'...
building '/nix/store/yi8kjzb12j8s02rqhpzm5gnwpm5a69yr-nixos-system-nixos-23.11.4703.c5101e457206.drv'...
stopping the following units: logrotate-checkconf.service, nscd.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service, systemd-update-done.service
NOT restarting the following changed units: systemd-journal-flush.service, systemd-logind.service, systemd-update-utmp.service, systemd-user-sessions.service, user-runtime-dir@1000.service, user@1000.service
activating the configuration...
setting up /etc...
setting up /bin...
setting up /bin/login...
setting up /sbin/init shim...
restarting systemd...
reloading user units for nixos...
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: systemd-journald.service
starting the following units: logrotate-checkconf.service, nscd.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-update-done.service
A dependency job for local-fs.target failed. See 'journalctl -xe' for details.
warning: the following units failed: tmp-.X11\x2dunix-X0.mount

× tmp-.X11\x2dunix-X0.mount - /tmp/.X11-unix/X0
     Loaded: loaded (/etc/fstab; generated)
     Active: failed (Result: resources)
      Where: /tmp/.X11-unix/X0
       What: /mnt/wslg/.X11-unix/X0
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)

Feb 24 15:49:11 nixos systemd[1]: tmp-.X11\x2dunix-X0.mount: Mount path /tmp/.X11-unix/X0 is not canonical (contains a symlink).
Feb 24 15:49:11 nixos systemd[1]: tmp-.X11\x2dunix-X0.mount: Failed to run 'mount' task: Too many levels of symbolic links
Feb 24 15:49:11 nixos systemd[1]: tmp-.X11\x2dunix-X0.mount: Failed with result 'resources'.
Feb 24 15:49:11 nixos systemd[1]: Failed to mount /tmp/.X11-unix/X0.
Feb 24 15:49:11 nixos systemd[1]: tmp-.X11\x2dunix-X0.mount: Mount path /tmp/.X11-unix/X0 is not canonical (contains a symlink).
Feb 24 15:49:11 nixos systemd[1]: tmp-.X11\x2dunix-X0.mount: Failed to run 'mount' task: Too many levels of symbolic links
Feb 24 15:49:11 nixos systemd[1]: tmp-.X11\x2dunix-X0.mount: Failed with result 'resources'.
Feb 24 15:49:11 nixos systemd[1]: Failed to mount /tmp/.X11-unix/X0.
warning: error(s) occurred while switching to the new configuration

[nixos@nixos:/mnt/c/Users/jojo]$
```

</details>

The total log was to large to put it into the issue directly. (GitHub has a limit of 65536 characters.) I therefore skipped some output of a few commands and replaced it with `[...]`. Here is the uncut version: [nixos-wsl-cannot-mount-log.txt](https://github.com/nix-community/NixOS-WSL/files/14393580/nixos-wsl-cannot-mount-log.txt).

## WSL version

```powershell
PS C:\Users\jojo> wsl --version
WSL-Version: 2.0.9.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.4046
PS C:\Users\jojo> Get-FileHash .\Downloads\nixos-wsl.tar.gz

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          4BF8560DF6950A295DB481BA2917AC76B09B856ABCD4EABE4842AF39D482EC25       C:\Users\jojo\Downloads\nixos-wsl.tar.gz
```

**Comment by SuperSandro2000** [comment]
This is expected since the PR I merged earlier but it came be ignored. It will be fixed with the next tarball release that contains the PR.

**Comment by SuperSandro2000** [comment]
> So I was just very unlucky to have installed NixOS just after you merged the PR?

Yes

> Is there a timeframe when the next Tarball release is coming?

probably with 24.05



> Restarting the computer did not fix the issue for me. Should I maybe delete the symlink at `/tmp/.X11-unix`?

Just restarting WSL should be enough.
Do you have set, that /tmp is not deleted on restart? But yeah, try that.

**Comment by JojOatXGME** [comment]
> Do you have set, that /tmp is not deleted on restart?

I have not changed any configuration after installing WSL. This means I also haven't set `boot.tmp.cleanOnBoot = true;`, which is disabled by default. By enabling this option and restarting WSL afterward, I fixed the problem. Maybe we should add some hock which deletes the symlink for legacy-purposes? I feel like there might be more users with an existing NixOS-WSL installation which may run into this problem.

**Comment by SuperSandro2000** [comment]
Counter suggestion: We just turn on boot.tmp.cleanOnBoot by default which really should be the case anyway. @K900 @nzbr opionions?

**Comment by JojOatXGME** [comment]
I don't have a strong opinion about whether `boot.tmp.cleanOnBoot` should be the default. I am usually using it, but I think temp-files are still deleted after 10 days even without this option. However, I feel like `boot.tmp.cleanOnBoot` is an option people my not expect to be changed by NixOS-WSL. So it might cause confusion that the system is behaving differently as documented by NixOS. Anyway, this is just my opinion. Here is also some code which should work, although I see that it may feel a bit messy to add this.

```nix
# Make sure the WSLg X11 socket is available if /tmp is mounted to something else
fileSystems."/tmp/.X11-unix/X0" = {
  device = "${cfg.wslConf.automount.root}/wslg/.X11-unix/X0";
  options = [ "bind" "x-systemd.requires=nixos-wsl-migration-x11mount.service" ];
};
# Remove symbolic link for WSLg X11 socket, which was created by NixOS-WSL until 2024-02-24
systemd.services.nixos-wsl-migration-x11mount = {
  description = "Removes symlink created by NixOS-WSL until 2024-02-24";
  unitConfig.ConditionPathIsSymbolicLink = "/tmp/.X11-unix";
  serviceConfig.Type = "oneshot";
  serviceConfig.RemainAfterExit = true;
  serviceConfig.ExecStart = "${pkgs.coreutils}/bin/rm /tmp/.X11-unix";
};
```

You could also create a different service called `nixos-wsl-migrations` which is supposed to make all the other migrations which may be needed in the future. I am just not sure if there might be cases where some migrations must be executed at different places in the dependency graph.

**Comment by sangemaru** [comment]
I just received the error described in OP having just downloaded the most recent release. @JojOatXGME , where does this code go?

First time installing NixOs, I have no idea where anything is.

**Comment by JojOatXGME** [comment]
> where does this code go?

The code in my last comment was a suggestion for a change within this repository. Just run the following command within your specific WSL instance of NixOS to fix the error:

```sh
sudo rm /tmp/.X11-unix
```

(The code I suggested above would basically run this code automatically whenever someone updates from a previous version to the current version.)

**Comment by JojOatXGME** [comment]
@fev4 Restarting WSL is not enough, as we discussed in later comments. You should delete the symlink at `/tmp/.X11-unix`. It should work afterward. I also just added a section “Workaround” into the issue description. Hopefully that helps if further people run into the issue before it is fixed.

> should I rerun the initial commands again after doing so?

It is not required, but I would still recommend rerunning `sudo nixos-rebuild switch` to see if the error is gone. Rerunning is technically not required because the new configuration is already applied before `sudo nixos-rebuild switch` runs into the error. I guess maybe WSLg may not work properly until you restart the WSL environment or rerun the command.

I hope this helps. 😄

**Comment by fev4** [comment]
ahh! @JojOatXGME TYVM! it worked!

**Comment by pmarreck** [comment]
Encountered same exact thing here. Fresh install after first hearing that I can even install NixOS on WSL, failed after my first "sudo nixos-rebuild switch" having changed nothing.

Unfortunately, before I found the cleanOnBoot possible solution, I tried the following based on an earlier troubleshooting suggestion I found, which I now don't know how to undo: `sudo mount -o remount,rw /tmp/.X11-unix`

**Comment by JojOatXGME** [comment]
@pmarreck No problem. `mount` does not make changes to persistent configurations. It is therefore enough to just restart the WSL environment.

**Comment by sangemaru** [comment]
```
[nixos@nixos:/mnt/c/Users/sange]$ sudo rm -rf /tmp/.X11-unix
rm: cannot remove '/tmp/.X11-unix/X0': Read-only file system
```

**Comment by JojOatXGME** [comment]
> ```
> [nixos@nixos:/mnt/c/Users/sange]$ sudo rm -rf /tmp/.X11-unix
> rm: cannot remove '/tmp/.X11-unix/X0': Read-only file system
> ```

Looks like you have already deleted the symlink before? You are not supposed to delete the context of `/tmp/.X11-unix`. The error of this issue was caused by a symlink at `/tmp/.X11-unix` which pointed at `/mnt/wslg/.X11-unix`. After you have removed the symlink, it is replaced by a mount point (which mostly looks like a directory).

**Comment by sangemaru** [comment]
> Looks like you have already deleted the symlink before

I don't think I have. I deleted it the first time yesterday according to instructions here, didn't fix it, then once I did it again I got this message

**Comment by coldino** [comment]
Well this was an unlucky time to install this for the first time I guess! Workaround worked fine for me.

**Comment by JojOatXGME** [comment]
> I deleted it the first time yesterday according to instructions here, didn't fix it, then once I did it again I got this message

According to the output of `rm` you shared previously, the problem we have so far discussed in this issue seems to be resolved. If it is still not working, maybe you can share the output of `sudo nixos-rebuild switch` again?

**Comment by JojOatXGME** [comment]
@nzbr Good to know. Just a note, I think activation scripts are usually executed before any systemd-unit gets started. Just in case the start order is the reason you are choosing the service. Although I guess you know that already.

Here are the activation scripts executed during boot: https://github.com/NixOS/nixpkgs/blob/5160edfab6d7cfe7752e1ec5922a90c5100eb634/nixos/modules/system/boot/stage-2-init.sh#L114-L117
Here are they executed during a switch: https://github.com/NixOS/nixpkgs/blob/1fc35bf4f48d6f18acc7b8c9d18b5de3c1e27668/nixos/modules/system/activation/switch-to-configuration.pl#L816-L820

Not sure if NixOS-WSL has its own implementation of a start-script. At the end, both solutions work according to my tests.
