### ISSUE TITLE
How to edit wsl.conf for initial config?

### ISSUE THREAD

**Issue by jkorinth** [nix-community/NixOS-WSL#428]
I cannot run the initial `sudo nix-channel --update` because I cannot use the same DNS server as the host Windows (company device). But I cannot deactivate the resolv.conf generation in wsl.conf because it is installed as a nix package and read-only. Manually editing /etc/resolv.conf works, but has no effect, I think I need to restart WSL? Any ideas?

**Comment by SuperSandro2000** [comment]
You could build a custom tarball on any linux system that has nix and then import that.

**Comment by jkorinth** [comment]
> You could build a custom tarball on any linux system that has nix and then import that.

Yes, that sounds like a good idea. When I try to build the tarball I get this error:

```
sudo nix run github:nix-community/NixOS-WSL#nixosConfigurations.modern.config.system.build.tarballBuilder
error: builder for '/nix/store/b28r9srala0nirliwv306fx1dc5v8qw3-system-path.drv' failed with exit code 1;
       last 2 log lines:
       > created 6251 symlinks in user environment
       > install-info: No such file or directory for gzip -d
       For full logs, run 'nix log /nix/store/b28r9srala0nirliwv306fx1dc5v8qw3-system-path.drv'.
error: 1 dependencies of derivation '/nix/store/v80yzh16yijaan7m14106355wz7lpm9k-nixos-system-nixos-23.11.20240209.20f65b8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3g01m0x2pl4qylhvfmb87jr5663ipysi-nixos-wsl-tarball-builder.drv' failed to build
```

I assume it has something to do with my system configuration?

**Comment by SuperSandro2000** [comment]
Please always past the full logs returned by ``nix log``.

**Comment by jkorinth** [comment]
Forgot to mention it, sorry, the two lines in the message above are the full log, nothing else.

**Comment by coffee0224** [comment]
Maybe you can set relative option in /etc/nixos/configuration.nix，refer [Configuration Options - NixOS-WSL](https://nix-community.github.io/NixOS-WSL/options.html#wslwslconfinteropappendwindowspath).
