### ISSUE TITLE
nvidia-container-toolkit-cdi-generator not work

### ISSUE THREAD

**Issue by qwqawawow** [nix-community/NixOS-WSL#433]
## Bug description
nvidia-container-toolkit-cdi-generator not work.
( meanwhile Nix would install LinuxKernel and Nvidia Drivers(Linux Version))

## To Reproduce

[Nvidia CDI-support doc](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html)

1.  nixpkgs 24.05 option  `virtualisation.containers.cdi.dynamic.nvidia.enable = true;`  provide [nvidia-container-toolkit-cdi-generator.service](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/nvidia-container-toolkit-cdi-generator/cdi-generate.nix#L29)

2. `systemctl status  nvidia-container-toolkit-cdi-generator.service`

## Logs
```
 /nix/store/6azwdj7ar1nlp2hn4ivfjgqd12pk0kgr-container-toolkit-container-toolkit-1.15.0-rc.3/bin/nvidia-ctk --debug cdi generate --library-search-path /usr/lib/wsl/lib/

DEBU[0000] Locating NVIDIA Container Toolkit CLI as nvidia-ctk
DEBU[0000] Locating "nvidia-ctk" in [/run/wrappers/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /usr/lib/wsl/lib /home/nixos/.nix-profile/bin /nix/profile/bin /home/nixos/.local/state/nix/profile/bin /etc/profiles/per-user/nixos/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin]
WARN[0000] Failed to locate nvidia-ctk: pattern nvidia-ctk not found
DEBU[0000] Using NVIDIA Container Toolkit CLI path nvidia-ctk
DEBU[0000] Is WSL-based system? false: could not load DXCore library: libdxcore.so: cannot open shared object file: No such file or directory
DEBU[0000] Is NVML-based system? false: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
DEBU[0000] Is Tegra-based system? false: /sys/devices/soc0/family file not found
INFO[0000] Auto-detected mode as "nvml"
ERRO[0000] failed to generate CDI spec: failed to create device CDI specs: failed to initialize NVML: ERROR_LIBRARY_NOT_FOUND

```

## WSL version
```
WSL version： 2.0.14.0
Kernel version： 5.15.133.1-1
WSLg version： 1.0.59
MSRDC version： 1.2.4677
Direct3D version： 1.611.1-81528511
DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version： 10.0.22631.3155
```

**Comment by SomeoneSerge** [comment]
I think this issue is better moved to NixOS/nixpkgs because the original module didn't account for the possibility that we'd need to mount libraries from somewhere other than the nix store (in this case the drivers deployed by WSL)

CC @ereslibre

**Comment by qwqawawow** [comment]
Ensure wsl.useWindowsDriver enabled

**Comment by ereslibre** [comment]
Thank you for the heads up @SomeoneSerge. I am not familiar with NixOS-WSL; is there anything we can do at the NixOS/nixpkgs level what would make your use case easier?

**Comment by qwqawawow** [comment]
> Thank you for the heads up @SomeoneSerge. I am not familiar with NixOS-WSL; is there anything we can do at the NixOS/nixpkgs level that would make your use case easier @qwqawawow?

I apologize for my carelessness and delayed response. Thank you very much for your contribution. That configuration is perfect for me.Thank you very very much🙇🙇

**Comment by ereslibre** [comment]
> I apologize for my carelessness and delayed response

No worries at all! Thank you for your feedback, it's really appreciated :)
