### ISSUE TITLE
`sudo` did not request for a password

### ISSUE THREAD

**Issue by rc-zb** [nix-community/NixOS-WSL#434]
## Bug description
`sudo` did not request for a password, even if a password has been specified via `users.users.*.hashedPassword`.

## To Reproduce
1. Install NixOS-WSL following the official tutorial.
2. Specify a mirror for the channel `nixos`.
3. Update the channels.
4. Upgrade the system.
5. Edit `/etc/nixos/configuration.nix` to add a user.
6. `sudo nixos-rebuild boot`
7. Quit WSL, wait for its extinguishing, and restart it.
8. **An error occurs.**
9. Restart again.
10. Try `sudo` something.
11. **No password needed. The program just proceeds.**

## Logs
During step 8 above:
```
<3>WSL (229) ERROR: CreateProcessParseCommon:745: getpwnam(nixos) failed 5
```

## WSL version
```
WSL 版本： 2.0.14.0
内核版本： 5.15.133.1-1
WSLg 版本： 1.0.59
MSRDC 版本： 1.2.4677
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22631.3235
```
## NixOS configuration
```nix
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixos-wsl/modules>
  ];

  wsl.enable = true;
  wsl.defaultUser = "rczb";
  boot.tmp.cleanOnBoot = true;

  users = {
    mutableUsers = false;
    users."rczb" = {
      description = "rczb";
      hashedPassword = ''$6$rpxAiwL3L8NeyC/1$gglAIYPMweizusTBOQqjuAXSH48NVcdpVmVtQDt9TQkFb1vvXfUaYGF2a0u18ec3M1LLGe6SCigLb.RVET0JE.'';
      isNormalUser = true;
      extraGroups = [ "wheel" ];
    };
  };

  system.stateVersion = "23.11";
}
```

**Comment by insurgent** [comment]
I believe the reason no sudo is required is because, after the error, you are not logged in as the new user. You are logged in as root. 
I've tried changing the default user as well as see the same error but the prompt and whoami command indicate root as the user.

Haven't figured out how to change the default so I just do "sudo login newusername" from the nixos user.

**Comment by rc-zb** [comment]
I haven't tried `whoami` yet. But invoking superuser commands like `nixos-rebuild switch` after step 9 without `sudo` preceded just failed with "Permission Denied" or something, let alone that it was a green `rczb`, instead of a red `root`, that was showed as a part of the prompt of Bash then.

**Comment by leoydm** [comment]
Maybe this will work https://github.com/nix-community/NixOS-WSL/discussions/71

**Comment by songpola** [comment]
I found this [PR](https://github.com/nix-community/NixOS-WSL/pull/406/files/379af73917816dd3d153b5862e648df3ba77ad32#diff-a5a331da9ca8c10252e5fc9591798d8e306301615e03c7558db741d9b2348aa6) about changing the username on an already installed system that works!

**Comment by antoineco** [comment]
If your user is part of the `wheel` group—like it is the case for the default WSL user—no password will be required for `sudo` commands, regardless of whether that user has a password set:

https://github.com/nix-community/NixOS-WSL/blob/34b95b3962f5b3436d4bae5091d1b2ff7c1eb180/modules/wsl-distro.nix#L171

Simply flip the boolean value in your configuration to disable the behavior.
