### ISSUE TITLE
Configure NIX_SSL_CERT_FILE with WSL2 and ZSCALER or similar enterprise Proxy

### ISSUE THREAD

**Issue by brokenpike** [nix-community/NixOS-WSL#435]
I cannot reliably or declaratively configure NIXOS-WSL to detect and abide my Zscaler SSL cert file.  nix-channel --update and nixos-rebuild switch due not function due to ssl errors.

**Comment by brokenpike** [comment]
I cannot reliably or declaratively configure NIXOS-WSL to detect and abide my Zscaler SSL cert file.  nix-channel --update and nixos-rebuild switch due not function due to ssl errors.

**Comment by SuperSandro2000** [comment]
Then you need to build a custom tarball with that certificate already included. See the readme on how to built that and the generel nixos options. For general support use the matrix channel or discussions

**Comment by jaycle** [comment]
Forgive me for jumping in to a closed issue, but was considering opening a discussion thread and then realized this can be solved without rebuilding the tarball by following this: https://github.com/NixOS/nix/issues/8022#issuecomment-2036710205.

The difficulties of trusting a cert with certain nixos commands I believe is a nixos issue, not nixos-wsl one.
