### ISSUE TITLE
/run/user/<id>/wayland-0 does not exist - Wayland GUI applications do not work

### ISSUE THREAD

**Issue by Pleune** [nix-community/NixOS-WSL#448]
## Bug description
With only the NixOS distribution, `/mnt/wslg/runtime-dir` contents are not linked to `/run/user/<id>/`. These links exist for Ubuntu/Debian/etc. WSL2 distributions. I can manually create these links, and wayland apps work perfectly. I cannot for the life of me figure out what component is supposed to create these links.

I think either something should be added to create these links, possibly as an override for the `user-runtime-dir@.service`, or something is getting in the way of WSL2 creating these links.

In my other WSL2 distributions, the files are linked during the launching of the wsl command. when entering as root and starting a login shell or the regular user, the files are not linked. This makes me think that normally, the WSL2 subsystem goes in and creates these files, but I am not sure of this.

## To Reproduce
Install NixOS WSL2 distrubution

## WSL version

```
WSL version: 2.2.2.0
Kernel version: 5.15.150.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296
```

**Comment by Pleune** [comment]
One successful workaround from https://github.com/microsoft/WSL/issues/8918 is to add the following configuation:

```
systemd.services."user-runtime-dir@" = {
  overrideStrategy = "asDropin";
  unitConfig.ConditionPathExists = "!/run/user/%i";
};
```

**Comment by nzbr** [comment]
Interesting, this must have come with a recent update. I couldn't reproduce it on my install at first, but after updating I have the same problem. I'll make a PR to integrate the workaround
