### ISSUE TITLE
doc bug: possibly missing "--version 2"

### ISSUE THREAD

**Issue by phip1611** [nix-community/NixOS-WSL#456]
I think there is a bug in the docs.

In the README it says `wsl --import NixOS $env:USERPROFILE\NixOS\ nixos-wsl.tar.gz`

but after that `wsl -d NixOS` results in a `HCS_E_CONNECTION_TIMEOUT`.

However, using `wsl --import NixOS $env:USERPROFILE\NixOS\ nixos-wsl.tar.gz --version 2` in the first place works.

**Comment by AlisterH** [comment]
This is right.
I have my default wsl version set to 1.  These days most users will have the default version set to 2, so they shouldn't have a problem.

I didn't get `HCS_E_CONNECTION_TIMEOUT`.
But I get this:
````
C:\Users\alister>wsl -d NixOS
when trying to exec the wrapped shell

Caused by:
    No such file or directory (os error 2)
````

**Comment by AlisterH** [comment]
In my case I want to use WSL1 because Windows filesystem access in WSL2 is so slow.
I can see old reports that the problem is just that NixOS has a 32bit bootstrap, and WSL1 doesn't support 32 bit binaries.  So I either need to configure a 64bit bootstrap or "QEMU and binfmt-support".
Is there any reason nixos-wsl couldn't include one of these solutions?

**Comment by SuperSandro2000** [comment]
> I can see old reports that the problem is just that NixOS has a 32bit bootstrap, and WSL1 doesn't support 32 bit binaries.

Where did you get that? I don't think thats true.

> Is there any reason nixos-wsl couldn't include one of these solutions?

Time burden. We only want to support systemd boot going forward because it is much closer to normal NixOS and saves us a bunch of hazle.

https://learn.microsoft.com/en-us/windows/wsl/compare-versions#comparing-features

**Comment by SuperSandro2000** [comment]
Also this is already mentioned in the docs https://nix-community.github.io/NixOS-WSL/install.html#system-requirements

**Comment by AlisterH** [comment]
> Also this is already mentioned in the docs https://nix-community.github.io/NixOS-WSL/install.html#system-requirements

It's all very well it being mentioned in the docs, but there's no point in providing commands that will create a WSL1 install, which won't work, if the machine happens to have WSL1 set as default.
