### ISSUE TITLE
Default distribution comes without networking enabled

### ISSUE THREAD

**Issue by danwdart** [nix-community/NixOS-WSL#46]
Bit of a catch-22, as I can't rebuild to enable networking, and I can't have networking without rebuilding.

Maybe having at least dhcpcd or dhclient will be good, or the `networking.dhcpcd.enable = true;` option as default?

**Comment by nzbr** [comment]
This does not seem to be an issue on the latest release. Feel free to re-open or open a new issue if you encounter another problem
