### ISSUE TITLE
How to use vscode in NixOS-WSL

### ISSUE THREAD

**Issue by poonai** [nix-community/NixOS-WSL#48]
In ubuntu version, I usually do `code .`  then vscode opens in windows with remote connection with ubuntu. 

Is it possible to have same workflow?

**Comment by felipeqq2** [comment]
Currently, `code` is not available in the $PATH (AFAIK), but there are some implementations to pass-through Windows environment to WSL (#45, #40, #41). I also had to use [vscode-remote-wsl-nixos](https://github.com/sonowz/vscode-remote-wsl-nixos) to patch node and make it work.

**Comment by poonai** [comment]
Understood thanks for the pointers. will try those methods.

**Comment by nzbr** [comment]
Using the latest release and some form of nixos vscode-server fix, this works now. If you need assistance, feel free to open a discussion
