### ISSUE TITLE
Help Needed - Failing upgrading to NixOS 24.05

### ISSUE THREAD

**Issue by kumkee** [nix-community/NixOS-WSL#482]
I'm trying to upgrade to NixOS 24.05, but failed. According to people on Matrix:#nixos-wsl, I don't have to wait for the new release from NixOS-WSL.
Below is what I did and the error messages I got. What did I do wrong?
```shell
# Changing system.stateVersion to "24.05"
$ sudo vim /etc/nixos/configuration.nix

$ sudo nix-channel --add https://channels.nixos.org/nixos-24.05-small nixos

$ sudo nixos-rebuild switch --upgrade
unpacking channels...
building Nix...
nix-instantiate: /nix/store/fgr12566n8yfj7jb119chr5vhshvwpym-gcc-12.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by nix-instantiate)
nix-instantiate: /nix/store/fgr12566n8yfj7jb119chr5vhshvwpym-gcc-12.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by nix-instantiate)
nix-instantiate: /nix/store/fgr12566n8yfj7jb119chr5vhshvwpym-gcc-12.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /nix/store/j7rp0y3ii1w3dlbflbxlv4g7hbaaz3bs-nix-2.18.2/lib/libnixexpr.so)
# ...
# there are more similar error messages
```

**Comment by SuperSandro2000** [comment]
Try unsetting LD_LIBRARY_PATH. Did you update the nixos-wsl channel?

> # Changing system.stateVersion to "24.05"

You should not do that unless you know what you are doing.

**Comment by kumkee** [comment]
> Try unsetting LD_LIBRARY_PATH. 

This does the trick. After commenting out `# sessionVariables.LD_LIBRARY_PATH = "${pkgs.stdenv.cc.cc.lib}/lib";`
I successfully upgraded to NixOS 24.05.

> > Changing system.stateVersion to "24.05"
> 
> You should not do that unless you know what you are doing.

Thanks for the reminder. I'll keep it to 23.11.
