### ISSUE TITLE
Can distrod help?

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/NixOS-WSL#49]
Is this helpful?
"Distrod is a systemd-based meta-distro for WSL2 that allows you to install Ubuntu, Arch Linux, Gentoo and many other distros with systemd in a minute, or make your current distro run systemd."

https://github.com/nullpo-head/wsl-distrod

**Comment by nzbr** [comment]
There is now a Discussion for this topic here: https://github.com/nix-community/NixOS-WSL/discussions/77
