### ISSUE TITLE
Docker using the host

### ISSUE THREAD

**Issue by ulrikstrid** [nix-community/NixOS-WSL#50]
Is it possible to use Docker from docker desktop like with other distros? It's basically the only thing that makes me keep using ubuntu as a escape hatch.

I currently get this output when trying:
```
> docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by SuperSandro2000** [comment]
``sudo docker ps`` does not fix that?

**Comment by Trundle** [comment]
`sudo` or adding your user to the `docker` group should indeed work.

**Comment by ulrikstrid** [comment]
I have since switched to nixos so I can't try it. But does it work with the "native" docker WSL support in Docker desktop?

**Comment by b3vis** [comment]
You can enable docker in NixOS-WSL yes however, there is a bug with iptables/nftables on 21.11 as systemd v249 which is the default in 21.11 breaks docker in NixOS-WSL. You can disable iptables using `--iptables=disable` as an extra option but it then means your containers aren't able to route out to the internet. It's all working fine on 21.05 though
