### ISSUE TITLE
Who wants to take over this project?

### ISSUE THREAD

**Issue by Trundle** [nix-community/NixOS-WSL#52]
As you might have noticed, I don't have the time or energy to really take care of `NixOS-WSL`. The project seems to have some users, so the best way forward would probably be to hand it over to someone who actively maintains it. Any suggestions or volunteers?

**Comment by SuperSandro2000** [comment]
I don't think I have enough time to help out with the project but when you find some bugs in nixpkgs you can ping me to get a merge.

**Comment by nzbr** [comment]
First of all, thank you for making this work in the first place! i am using NixOS in WSL on a daily basis and have made some improvements in my own nix config, which i recently integrated into my fork of this repo. It would be sad to see the project die, so i'd be willing to adopt it

**Comment by b3vis** [comment]
I'd like to throw my hat into the ring and offer to help @nzbr and collaborate. Could we apply to get this moved to the nix-community organisation

**Comment by nzbr** [comment]
gettting this into nixos-community would be great. do you happen to know who we'd have to talk to about that?

**Comment by SuperSandro2000** [comment]
for example @mic92

**Comment by Mic92** [comment]
Let me know if you need an invite to nix-community. Than you can move the project yourself.

**Comment by b3vis** [comment]
that would be fantastic @Mic92 I think @nzbr and I want to collaborate on this project

**Comment by Mic92** [comment]
I invited both @nzbr and @Trundle

**Comment by Trundle** [comment]
I think moving this project to nix-community is a great step forward. Thank you @nzbr, @b3vis and @Mic92.

**Comment by Mic92** [comment]
@Trundle who should I give commit rights?

**Comment by nzbr** [comment]
@Mic92: Considering, that @Trundle has not responded to this thread for more than a month, can you grant maintainer permissions to me and @grantbevis? Judging by the comments above, this seems to be @Trundle's intention and would enable us to continue development on this project

**Comment by Trundle** [comment]
Sorry, yes, what @nzbr said.

**Comment by sielicki** [comment]
I’m using nzbrs fork on a couple machines today. Looking forward to this getting a bit more attention, I think WSL is a good first platform for people new to nix.

**Comment by grantbevis** [comment]
I’ve been using this fork for work and I’ve had some quirks with DNS but this is due to our corporate VPN interfering with DNS settings on my machine. Using the custom kernel I was able to get docker running happily under 21.11 too

**Comment by Mic92** [comment]
will do.

**Comment by Mic92** [comment]
I created a team with access to this repo: https://github.com/orgs/nix-community/teams/nixos-wsl

**Comment by grantbevis** [comment]
Thanks @Mic92
