### ISSUE TITLE
Provide a `options.wsl.conf.extraOptions` value for other `/etc/wsl.conf` values

### ISSUE THREAD

**Issue by Frontear** [nix-community/NixOS-WSL#559]
As per [microsoft documentation](https://learn.microsoft.com/en-us/windows/wsl/wsl-config), there are a lot of WSL configuration knobs you can set. If you use `config.wsl.enable` however, `/etc/wsl.conf` becomes a read-only symlink into the store, and there is no module option available to add your own customized options. This is a fairly simply problem to fix, and would greatly reduce maintainer burden on needing to keep up and update the module as microsoft changes things.

**Comment by SuperSandro2000** [comment]
If we are going to change that option, it is going to be a freeform type.

**Comment by Frontear** [comment]
> If we are going to change that option, it is going to be a freeform type.

Agreed! That is how I intended for it as well, not just for the options not covered, but for all possible options. Leaving it up to the user.

Main motivation for this was because I wanted to set swap knobs, but couldn't without imperatively declaring the file.
