### ISSUE TITLE
Option to increase memory and cores?

### ISSUE THREAD

**Issue by Yash-Garg** [nix-community/NixOS-WSL#564]
## Problem
I could not find a way to increase the default memory and cores values in the flake, is there any chance I missed it?

![image](https://github.com/user-attachments/assets/79d65eed-168e-4630-86a6-ac43dd89cacd)

**Comment by nzbr** [comment]
That needs to be done globally, not on a per-distro basis, so it won't be possible

**Comment by Yash-Garg** [comment]
@nzbr yeah my bad, found it in the docs!
