### ISSUE TITLE
[Windows 11] systemctl --user fails with release 20.09-0cfd08f4881 

### ISSUE THREAD

**Issue by erik-smit** [nix-community/NixOS-WSL#57]
On Windows 11
```
[nixos@nixos:~]$ systemctl --user status
Failed to connect to bus: No such file or directory
```

strace shows `connect(3, {sa_family=AF_UNIX, sun_path="/mnt/wslg/runtime-dir/systemd/private"}, 40) = -1 ENOENT (No such file or directory)`. This pointed me to Windows 11/wslg.

Replacing `/etc/nixos/syschdemd.sh` with https://raw.githubusercontent.com/nix-community/NixOS-WSL/main/syschdemd.sh fixes `systemctl --user`.

However, now vscode-server breaks. Going with https://raw.githubusercontent.com/nzbr/NixOS-WSL/main/syschdemd.sh fixes also this part.

**Comment by nzbr** [comment]
Merging the fix is currently blocked by #52
