### ISSUE TITLE
"The system cannot find the path specified" for files in ~/.config

### ISSUE THREAD

**Issue by Wraaath** [nix-community/NixOS-WSL#572]
## Bug description

When using the Windows file explorer and opening files from my user home directory's .config (`/home/myuser/.config/example.txt`), I get the error "The system cannot find the path specified". This does not happen when opening files from, eg. `/home/myuser/some-git-repo/example.txt`. \ 
This doesn't seem to be an issue when using other WSL distros, atleast from what I can find online. I think it's a permission issue, with my Windows user not having the same permissions as my Unix user. But I really don't know. Am I missing something obvious?

## To Reproduce

1. Install NixOS-WSL
2. Change the username with `wsl.defaultUser` according to [the docs](https://nix-community.github.io/NixOS-WSL/how-to/change-username.html)
3. Link config-files (git, mpv, ...) to my users home directory with Home Manager using `home.file`:
```nix
{ lib, pkgs, ... }:

{
  config = {
    home.packages = [ pkgs.unstable.mpv ];

    # Link the shared MPV configuration
    home.file.".config/mpv" = {
      source = ./config;
      recursive = true;
    };
  };
}
```
4. Enter `~/.config` and do `explorer.exe .`
5. Try to open files (for example with Notepad)
6. Try to open files that aren't linked using Home Manager, and get same error.

## Logs
Usually this error:
```
The system cannot find the path specified
```
or this:
```
Cannot find the \\wsl.localhost\NixOS\home\myuser\.config\git\config.txt file.
```
or opening with VSCode gives an empty file.

## WSL version

```
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4169
```

**Comment by SuperSandro2000** [comment]
The home-manager files probably won't work because windows cannot resolve the symlink.

**Comment by Wraaath** [comment]
Oh yeah of course. I don't know why I didn't think about that. Man that's too bad..
