### ISSUE TITLE
Unable to use GPU inside NVIDIA docker container

### ISSUE THREAD

**Issue by fyang93** [nix-community/NixOS-WSL#578]
## Bug description

I tried to use the NVIDIA Docker container on NixOS 24.05. According to the official docs, I set `hardware.nvidia-container-toolkit.enable = true;` and also enabled `wsl.useWindowsDriver = true;`. After setting the environment variable `NIX_LD_LIBRARY_PATH = "/usr/lib/wsl/lib"`, I was able to get GPU information using `nvidia-smi`, confirming that it matches the output on Windows. Next, I checked that the CDI file exists and is valid by running `cat /var/run/cdi/nvidia-container-toolkit.json`; however, I still cannot access to the nvidia driver inside the container properly, the error message is attached in Logs.
It seems like the NVIDIA container toolkit did not correctly locate the driver files.

## To Reproduce
- Set `wsl.useWindowsDriver = true;` and `hardware.nvidia-container-toolkit.enable = true;` in flake
- Set `NIX_LD_LIBRARY_PATH = "/usr/lib/wsl/lib"` in shell

## Logs
```nushell
❯ docker run --rm -it --device=nvidia.com/gpu=all ubuntu:latest /bin/bash
root@ac812a4a8cd7:/# nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```

## WSL version

```
WSL Version： 2.3.24.0
Kernel version： 5.15.153.1-2
WSLg version： 1.0.59
MSRDC version： 1.2.5620
Direct3D version： 1.611.1-81528511
DXCore version： 10.0.26100.1-240331-1435.ge-release
Windows version： 10.0.22631.4317
```

**Comment by SuperSandro2000** [comment]
Is this maybe duplicated with #454 ?

**Comment by fyang93** [comment]
> Is this maybe duplicated with #454 ?

The solution mentioned in that issue does not solve my problem.
Setting `hardware.opengl.setLdLibraryPath = true;` does not make any difference in my case :\

**Comment by fyang93** [comment]
```
╭────┬─────────────────────────────────────────────╮
│  0 │ /usr/lib/wsl/lib/libcuda.so                 │
│  1 │ /usr/lib/wsl/lib/libcuda.so.1               │
│  2 │ /usr/lib/wsl/lib/libcuda.so.1.1             │
│  3 │ /usr/lib/wsl/lib/libcudadebugger.so.1       │
│  4 │ /usr/lib/wsl/lib/libd3d12.so                │
│  5 │ /usr/lib/wsl/lib/libd3d12core.so            │
│  6 │ /usr/lib/wsl/lib/libdxcore.so               │
│  7 │ /usr/lib/wsl/lib/libnvcuvid.so              │
│  8 │ /usr/lib/wsl/lib/libnvcuvid.so.1            │
│  9 │ /usr/lib/wsl/lib/libnvdxdlkernels.so        │
│ 10 │ /usr/lib/wsl/lib/libnvidia-encode.so        │
│ 11 │ /usr/lib/wsl/lib/libnvidia-encode.so.1      │
│ 12 │ /usr/lib/wsl/lib/libnvidia-ml.so.1          │
│ 13 │ /usr/lib/wsl/lib/libnvidia-opticalflow.so   │
│ 14 │ /usr/lib/wsl/lib/libnvidia-opticalflow.so.1 │
│ 15 │ /usr/lib/wsl/lib/libnvoptix.so.1            │
│ 16 │ /usr/lib/wsl/lib/libnvwgf2umx.so            │
│ 17 │ /usr/lib/wsl/lib/nvidia-smi                 │
╰────┴─────────────────────────────────────────────╯
```
Here are all files inside `/usr/lib/wsl/lib/`, there is only `libnvidia-ml.so.1` but no `libnvidia-ml.so`. I tried creating a symlink, but no luck

**Comment by fyang93** [comment]
I just looked into the [source code](https://github.com/nix-community/NixOS-WSL/blob/24ab2f9ad309b1bba89644116656139dde706833/modules/wsl-distro.nix#L99), looks like it doesn’t even link the file `/usr/lib/wsl/lib/libnvidia-ml.so` at all. Isn't this a critical bug?
```nix
extraPackages = mkIf cfg.useWindowsDriver [
  (pkgs.runCommand "wsl-lib" { } ''
    mkdir -p "$out/lib"
    # # we cannot just symlink the lib directory because it breaks merging with other drivers that provide the same directory
    ln -s /usr/lib/wsl/lib/libcudadebugger.so.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libcuda.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libcuda.so.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libcuda.so.1.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libd3d12core.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libd3d12.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libdxcore.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvcuvid.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvcuvid.so.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvdxdlkernels.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvidia-encode.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvidia-encode.so.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvidia-ml.so.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvidia-opticalflow.so "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvidia-opticalflow.so.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvoptix.so.1 "$out/lib"
    ln -s /usr/lib/wsl/lib/libnvwgf2umx.so "$out/lib"
    ln -s /usr/lib/wsl/lib/nvidia-smi "$out/lib"
  '')
];
};
```

**Comment by shikanime** [comment]
To solve the nvidia-smi problem when nix-ld is also enabled, you need to add the "wsl-lib" to `program.nix-ld.packages` as `useWindowsDriver` only set it up for `OpenGL`. Similarly I believe that to make docker work, you should also set up the `virtualisation.docker.extraPackages`.

**Comment by fyang93** [comment]
@shikanime Thank you for the information!
I guess you mean to add wsl-lib to programs.nix-ld.libraries, but I can't find this library in pkgs. Do I need to use some library from the nixos-wsl input?

**Comment by shikanime** [comment]
@fyang93 I was referring to the "wsl-lib" used by useWindowsDriver.

**Comment by shikanime** [comment]
Ok, I just tested it, it seems that the CDI generated by `nvidia-container-toolkit` doesn't really work for WSL.
You need to generate your own `nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml` and use the following configuration:
```nix
virtualisation.docker = {
  enable = true;
  daemon.settings.features.cdi = true;
  daemon.settings.cdi-spec-dirs = ["/etc/cdi"];
};
```

**Comment by 573** [comment]
https://github.com/nix-community/NixOS-WSL/discussions/487#discussioncomment-11180666

**Comment by shikanime** [comment]
Normally it is the job of the `nvidia-container-toolkit` to generate the CDI, just to confirm my hypothesis, I tried it on my machine and yes it didn't work properly because of missing libraries, on WSL you should disable the executables provided by the generated CDI and it looks fine so far.
```nix
hardware.nvidia-container-toolkit = {
  enable = true;
  mount-nvidia-executables = false;
};
```

```shell
❯ docker run --rm --device nvidia.com/gpu=all ubuntu nvidia-smi -L     
GPU 0: NVIDIA GeForce RTX 2070 with Max-Q Design (UUID: GPU-724d28f9-c8dc-91b2-6927-e1661f089935)
```

**Comment by nzbr** [comment]
@shikanime Would you be willing to create a PR to add this to the how-to section of the docs? I can't be of much help with this topic unfortunately, because the laptop I currently use primarily does not have an nvidia GPU

**Comment by fyang93** [comment]
@shikanime  Sorry for the delayed response. Your solution was spot on and it worked like a charm, really appreciate the assist! 🙌

**Comment by shikanime** [comment]
```
         🌸＞ ' ' フ
         | . _  _l    
        ／` ミ＿xノ     < I'll do it somehow this week, unless I'm lazing around like my cat.
       / .     |    
      /   ヽ . ﾉ
     │ . |  |  |
 ／￣| .  |  |  |
 | (￣ヽ＿_ヽ_)__)
 ＼二つ
```

**Comment by Atry** [comment]
I think we also need to disable an assertion in NixOS: https://github.com/NixOS/nixpkgs/pull/362197

**Comment by inschrift-spruch-raum** [comment]
> I just looked into the [source code](https://github.com/nix-community/NixOS-WSL/blob/24ab2f9ad309b1bba89644116656139dde706833/modules/wsl-distro.nix#L99), looks like it doesn’t even link the file `/usr/lib/wsl/lib/libnvidia-ml.so` at all. Isn't this a critical bug?

This is my first time working with Nix, and I'm not very clear about how the system works.
@SuperSandro2000 
I'm curious here, since the code has already been set up, why do we still need to manually add it to nix-ld?

And the missing file mentioned here does indeed exist, but I'm also curious why the system can still work properly without it.

**Comment by inschrift-spruch-raum** [comment]
At the same time, it seems that my ctk can't correctly control the location of the files.
```bash
$ sudo nvidia-ctk cdi generate --mode=wsl --output=/etc/cdi/nvidia.yaml
WARN[0000] Failed to locate nvidia-cdi-hook: pattern nvidia-cdi-hook not found
WARN[0000] Failed to load ldcache: open /etc/ld.so.cache: no such file or directory
INFO[0000] Using /run/opengl-driver/lib/libnvidia-ml.so.1
WARN[0000] Failed to load ldcache: open /etc/ld.so.cache: no such file or directory
WARN[0000] Ignoring error in locating libnvidia-sandboxutils.so.1: dlopen libnvidia-sandboxutils.so.1 failed
pattern libnvidia-sandboxutils.so.1 not found
libnvidia-sandboxutils.so.1: not found
WARN[0000] Failed to init nvsandboxutils: ERROR_LIBRARY_LOAD; ignoring
WARN[0000] Could not determine driver version: libnvsandboxutils is not available
failed to initialize nvml: Unable to load the NVML library
INFO[0000] Selecting /dev/dxg as /dev/dxg
WARN[0000] Found multiple driver store paths: [/usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589 /usr/lib/wsl/drivers/u0414773.inf_amd64_c481553f385792e2]
INFO[0000] Using WSL driver store paths: [/usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589 /usr/lib/wsl/drivers/u0414773.inf_amd64_c481553f385792e2]
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libcuda.so.1.1 as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libcuda.so.1.1
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libcuda_loader.so as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libcuda_loader.so
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvidia-ptxjitcompiler.so.1 as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvidia-ptxjitcompiler.so.1
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvidia-ml.so.1 as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvidia-ml.so.1
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvidia-ml_loader.so as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvidia-ml_loader.so
INFO[0000] Selecting /usr/lib/wsl/lib/libdxcore.so as /usr/lib/wsl/lib/libdxcore.so
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvdxgdmal.so.1 as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/libnvdxgdmal.so.1
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/nvcubins.bin as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/nvcubins.bin
INFO[0000] Selecting /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/nvidia-smi as /usr/lib/wsl/drivers/nvtfsi.inf_amd64_22a6b37893eb5589/nvidia-smi
INFO[0000] Generated CDI spec with version 1.0.0

$ sudo docker run --rm --device nvidia.com/gpu=all ubuntu nvidia-smi -L
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "nvidia-smi": executable file not found in $PATH
```

**Comment by inschrift-spruch-raum** [comment]
> You need to generate your own `nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml` and use the following configuration

I have already reported this to the nixpkgs upstream. It is no longer needed now (unstable).
https://github.com/NixOS/nixpkgs/issues/473545
