### ISSUE TITLE
WSL --import flag syntax update??

### ISSUE THREAD

**Issue by Keshav13142** [nix-community/NixOS-WSL#581]
## Bug description
The wsl command to import the tar file does not seem to work for the latest wsl version

## To Reproduce
- Install latest windows version (24H2 0S Build 26100.2033)
- Enable/Install wsl
- Run the command to import nixos-wsl tar file

  ```ps1
   wsl --import NixOS $env:USERPROFILE\NixOS\ nixos-wsl.tar.gz --version 2
  ```
## Logs
Running the command given in the readme just prints the `wsl --help` output

## WSL version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2033

## Screenshot of the new syntax
![image](https://github.com/user-attachments/assets/70afdd97-88a8-4c65-b331-85cb6805cc87)

## Possible fix
I just added the `<InstallLocation>` to be the current directory and it seemed to work.

```ps1
wsl --import "NixOS" . "C:\Users\User\NixOS\nixos-wsl.tar.gz" --version 2
```

**Comment by SuperSandro2000** [comment]
You executed the command in cmd, right? I think the command we are using is for powershell and if you don't treat the final slash as an escape character, it does the same thing

**Comment by Keshav13142** [comment]
> You executed the command in cmd, right? I think the command we are using is for powershell and if you don't treat the final slash as an escape character, it does the same thing

I was using powershell core to execute all the commands.

**Comment by nzbr** [comment]
In that case `$env:USERPROFILE\NixOS\` should just expand to `C:\Users\User\NixOS\` for you, so that would be the value for `<InstallLocation>`

**Comment by Keshav13142** [comment]
OMG I'm so stupid 🥲, I named my folder Nixos instead of NixOS, so when I ran the command given in the readme it throwed an error. I'll see myself out 🚶.
