### ISSUE TITLE
[FR] out-of-the-box support for linking Windows ssh binaries

### ISSUE THREAD

**Issue by tminich** [nix-community/NixOS-WSL#587]
## Problem
Using the windows ssh binaries provided by Microsoft allows you to use the ssh-agent running on the windows side without further setup. As far as I can tell and in my experience so far, they work perfectly fine inside wsl symlinked.

## Solution
For now I'm using wsl.extraBin, but I think it would be great if there was a out-of-the-box solution to link them all by just providing the source path.

**Comment by SuperSandro2000** [comment]
This probably opens a new can of worms.
