### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by sielicki** [nix-community/NixOS-WSL#62]
Current tarball from feb of last year is essentially unusable given the amount of required changes that were held up for so long. 

I think this is urgent as it's very frustrating for someone to come across this repo and not realize it's broken. Maybe consider just pushing a readme change to master to denote that the current tarball can't be used and that you have to build it yourself for now.

**Comment by nzbr** [comment]
I have just created a new release with the current changes. I'll start working on a 21.11 release soon
