### ISSUE TITLE
/bin/sh: line 1: cd: /root: Permission denied

### ISSUE THREAD

**Issue by michas2** [nix-community/NixOS-WSL#72]
I imported a fresh NixOS using:
```
wsl --import NixOS .\NixOS\ .\Downloads\nixos-wsl-installer-fixed.tar.gz --version 2
```

When I start it I get:
```
wsl -d NixOS
/bin/sh: line 1: cd: /root: Permission denied

[nixos@nixos:~]$
```
(Also `/mnt/*` is not mounted.)

After restarting the distro it seems to work again:
```
> wsl -t NixOS
> wsl -d NixOS
Copying /usr/share/applications
Copying /usr/share/icons
setting up /etc...

[nixos@myhostname:/mnt/c/Users/michas]$
```

**Comment by dmcclccam** [comment]
I had the same problem. As a workaround I created a script and used it in Windows Terminal to start NixOS.

```sh
# C:\Users\danil\NixOS.bat

C:\Windows\system32\wsl.exe -t NixOS

C:\Windows\system32\wsl.exe -d NixOS
```

<img width="520" alt="image" src="https://user-images.githubusercontent.com/9166907/163419604-c5e3284f-0225-47a3-a811-dd285bba65ab.png">

**Comment by nzbr** [comment]
The script should not be needed. `/mnt` not being mounted should only be the case when the disto is started for the first time after it is installed

**Comment by michas2** [comment]
Looks like Windows terminal will try to start the terminal in home directory, which will always trigger the cd error:
```
>wsl -d NixOS --cd ~
/bin/sh: line 1: cd: /root: Permission denied
```

My current workaround is explicitly specifying "/home/nixos" instead of "~".
I'm still curious. Where does the error come from and what is the exact reason?

**Comment by nzbr** [comment]
When you start NixOS, a root shell is started. syschdemd.sh then changes to the namespace where systemd runs as PID 1 and drops to a shell as the nixos user. So when the distro is started, `~` resolves to `/root`
