### ISSUE TITLE
Docker Desktop WSL2 not working

### ISSUE THREAD

**Issue by hschaeidt** [nix-community/NixOS-WSL#89]
## Bug description
When I enable the option `docker.enable = true;` in my `configuration.nix` I expect then to see my running docker images in Docker Desktop for Windows when executing `docker ps`. Instead I get:

```bash
$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

So my first thought here is, why is it trying to connect to the local docker socket and not the proxy?

After some trials and errors I finally found following hint:

```bash
/mnt/wsl/docker-desktop/docker-desktop-proxy -docker-desktop-root /mnt/wsl/docker-desktop
bash: /mnt/wsl/docker-desktop/docker-desktop-proxy: No such file or directory
```

On my system it seems the name is different, instead when running this command, everything works:

```bash
/mnt/wsl/docker-desktop/docker-desktop-user-distro proxy --docker-desktop-root /mnt/wsl/docker-desktop
```

Before submitting a Pull-Request with a fix that works only for me, I want to figure out how comes that my system behaves differently from the others. In the next step I will let you know the versions of NixOS-WSL and Docker Desktop I use, to let you potentially reproduce this issue.

## To Reproduce

- Host: Windows 11 Pro; Version: 21H2; OS build: 22000.613
- This is the tarball I used: https://github.com/nix-community/NixOS-WSL/releases/download/21.11-d89f18a1/nixos-wsl-installer-fixed.tar.gz
- Docker Desktop for Windows Version 4.7.1 (77678)
  - Settings > Resources > WSL Integration
  - [x] Enable Integration with my default WSL distro
  - [ ] NixOS
  - [x] Ubuntu
  - NixOS is **not** my default WSL distro

**Comment by hschaeidt** [comment]
I am having another issue now with Docker Desktop Integration now. The volume mounting seems not to be working as expected. For example when I run:

```
$ docker run -it -v /home/nixos:/test alpine /bin/sh
/ # ls -la /test
total 4
drwxr-xr-x    2 root     root            40 May  3 08:04 .
drwxr-xr-x    1 root     root          4096 May  3 08:33 ..
/ #
```

When I do the same in my Ubuntu WSL machine, the home directory gets mounted. What does this image differently that happens when I turn on the WSL integration toggle in the Docker Desktop Settings for another distro?

Settings > Resources > WSL Integration
NixOS is turned off -> doesn't work
Ubuntu is turned on -> works as expected

Any ideas of to debug this further are warmly welcome.

**Comment by nzbr** [comment]
The different path seems to be a change in Docker Desktop. I just installed it, and it has the new file name on my machine as well. Mounting directories doesn't work for me either, though I think it has worked in the past (before docker changed the binary)

**Comment by hschaeidt** [comment]
Thank you for taking the time to test and confirm the issue here.

I tried out some further steps in order to isolate/reproduce the issue with the volume mounting. However without success. But to have it documented, I will describe what I have tried so far.

<details>
<summary>TLDR: All the following was run without any success. Click to expand.</summary>

My first approach was to find the differences between a working Ubuntu WSL and the NixOS WSL.

```bash
# Ubuntu WSL
$ which docker
/mnt/c/Program Files/Docker/Docker/resources/bin/docker
```

```bash
# NixOS WSL
$ which docker
/home/mayflower/.nix-profile/bin/docker
```

So the first difference I thought could be root of this issue is that we are not using the mounted wsl binary in the NixOS module.
WSL does a lot of docker binary symlinking in the `/usr/bin` directory

```bash
# NixOS WSL (to have the stripped down output, on the Ubuntu WSL this directory is full of links)
$ ls -la /usr/bin/
total 16
drwxr-xr-x 2 root root 4096 May  5 10:07 .
drwxr-xr-x 6 root root 4096 May  1 11:05 ..
lrwxrwxrwx 1 root root   56 May  5 10:07 com.docker.cli -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/com.docker.cli
lrwxrwxrwx 1 root root   48 May  5 10:07 docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
lrwxrwxrwx 1 root root   56 May  5 10:07 docker-compose -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose
lrwxrwxrwx 1 root root   59 May  5 10:07 docker-compose-v1 -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose-v1
lrwxrwxrwx 1 root root   71 May  5 10:07 docker-credential-desktop.exe -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-credential-desktop.exe
lrwxrwxrwx 1 root root   65 May  5 10:07 env -> /nix/store/ndkb1hkd009fch9dkzs31p9b7sa61s61-coreutils-9.0/bin/env
lrwxrwxrwx 1 root root   50 May  5 10:07 hub-tool -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/hub-tool
```

My first approach was to remove the `docker` and `docker-compose` package from the `./modules/docker-desktop.nix` in order to use the symlinked binaries here too, like in an Ubuntu WSL setup. My assumption was that this way everything should work as expected.
However for some reason I was not able to get it running, every try resulted in:

```bash
# NixOS WSL
$ docker ps
fork/exec /usr/bin/com.docker.cli: no such file or directory
```

As I couldn't figure out, why this is not working, because the file does actually exist, I tried the opposite way around. Using the exact same `docker` and `docker-compose` binary from nixpkgs in the Ubuntu image using `home-manager`.
In order to have the exact same integration I decided to further disable any WSL integration in the Docker-Desktop settings and to start the proxy manually in the Ubuntu image, like we do in the `docker-desktop-proxy.service` in the NixOS image.

However everything still works fine in the Ubuntu image.
</details>

**Comment by nzbr** [comment]
> fork/exec /usr/bin/com.docker.cli: no such file or directory
That happens because the docker binary is linked against some dynamic library that it can not find in NixOS. That's why usually, when a pre-compiled binary is packaged for NixOS, it gets modified by `patchelf` to adjust the library paths to their locations in the nix store. You can find out, which libraries docker is trying to load by running `ldd /usr/bin/com.docker.cli`

**Comment by hschaeidt** [comment]
Good hint! However we are reaching the edge of my operating system knowledge here.

```bash
# NixOS WSL
$ ldd /usr/bin/com.docker.cli
        linux-vdso.so.1 (0x00007fffea5ed000)
        libpthread.so.0 => /nix/store/qjgj2642srlbr59wwdihnn66sw97ming-glibc-2.33-123/lib/libpthread.so.0 (0x00007f6ae6ea3000)
        libdl.so.2 => /nix/store/qjgj2642srlbr59wwdihnn66sw97ming-glibc-2.33-123/lib/libdl.so.2 (0x00007f6ae6e9e000)
        libc.so.6 => /nix/store/qjgj2642srlbr59wwdihnn66sw97ming-glibc-2.33-123/lib/libc.so.6 (0x00007f6ae6cc9000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/qjgj2642srlbr59wwdihnn66sw97ming-glibc-2.33-123/lib64/ld-linux-x86-64.so.2 (0x00007f6aea2d7000)
```

For me it looks like all dependencies are being resolved, I am not really sure about how to dig deeper at this point in time. Also I'm not sure if this is really relevant, as using the `nixpkgs.docker` binary in a Ubuntu distro with the running proxy works too.

**Comment by davegallant** [comment]
Can also confirm that https://github.com/nix-community/NixOS-WSL/pull/90 fixes docker integration on Windows 11 Version 21H2 (OS Build 22000.778) and Docker Desktop Version 4.10.0 (82025).

**Comment by GuillaumeDesforges** [comment]
Today I'm getting the same issues. I've set `wsl.docker-desktop.enable = true;` but service fails. In journactl I can see:

```
docker-desktop-proxy-start[298]: /nix/store/g96qs4zb4m8sbhcs712l1ks4vqpsdifc-unit-script-docker-desktop-proxy-start/bin/docker-desktop-proxy-start: line 3: /mnt/wsl/docker-desktop/docker-desktop-user-distro: No such file or directory
```

In fact, `/mnt/wsl` is empty:

```
$ ls -a /mnt/wsl
. ..
```

I have Docker Desktop installed, with WSL 2 backend and "Settings -> Resources -> WSL Integration" enabled.

**Comment by nzbr** [comment]
It somtimes is a little difficult to get working correctly. Can you try the following:
1. Quit all WSL instances with `wsl --shutdown`
2. Restart Docker Desktop
3. Start NixOS and check if the files are now present

That's at least what it sometimes takes to get it working on my machine
